// คู่รัก — [ไทย, English]
// open: เปิดบทสนทนาแบบสบาย ๆ  ·  mid: ชวนนึกถึงความทรงจำและคุณค่า  ·  deep: เชิงลึก/จิตวิทยา
export const open = [
  ['ถ้าวันนี้ได้หยุดงานหนึ่งวันพร้อมกัน อยากใช้วันนั้นทำอะไร?', 'If we both had today off, how would you want to spend it?'],
  ['อาหารมื้อไหนที่กินด้วยกันแล้วยังจำรสชาติได้จนถึงตอนนี้?', 'Which meal we shared do you still remember the taste of?'],
  ['เพลงไหนที่ฟังแล้วนึกถึงอีกฝ่ายทันที?', 'Which song instantly reminds you of your partner?'],
  ['ถ้าเราสองคนเป็นตัวละครในหนัง จะเป็นหนังแนวไหน?', 'If we were characters in a movie, what genre would it be?'],
  ['ที่เที่ยวในฝันที่อยากไปด้วยกันสักครั้งคือที่ไหน?', 'What is one dream destination you want us to visit together?'],
  ['ของขวัญชิ้นไหนที่ได้รับจากอีกฝ่ายแล้วประทับใจที่สุด?', 'Which gift from your partner touched you the most?'],
  ['อะไรคือสิ่งแรกที่สังเกตเห็นในตัวอีกฝ่าย?', 'What was the first thing you noticed about your partner?'],
  ['ถ้าต้องตั้งชื่อเล่นใหม่ให้อีกฝ่าย จะตั้งว่าอะไร?', 'If you had to give your partner a new nickname, what would it be?'],
  ['กิจกรรมวันหยุดแบบไหนที่อยากทำด้วยกันบ่อยขึ้น?', 'What weekend activity would you like us to do more often?'],
  ['ถ้าได้เปิดร้านด้วยกันหนึ่งร้าน จะเป็นร้านอะไร?', 'If we opened a shop together, what kind would it be?'],
  ['มุมไหนในบ้านหรือในเมืองที่รู้สึกว่าเป็น "ที่ของเรา"?', 'Which place at home or in town feels like "our spot"?'],
  ['ช่วงเวลาไหนของวันที่ชอบใช้เวลาด้วยกันที่สุด?', 'What time of day do you most enjoy spending together?'],
  ['ถ้าต้องเลือกขนมหนึ่งอย่างแทนความสัมพันธ์ของเรา จะเลือกอะไร?', 'If our relationship were a dessert, which one would it be?'],
  ['เรื่องตลกเรื่องไหนของเราที่เล่าให้ใครฟังก็หัวเราะ?', 'Which funny story about us makes everyone laugh?'],
  ['ถ้าได้ย้อนไปเดตครั้งแรกอีกครั้ง อยากเปลี่ยนอะไรไหม?', 'If we could redo our first date, would you change anything?'],
  ['ซีรีส์หรือหนังเรื่องไหนที่อยากดูด้วยกันตั้งแต่ต้นจนจบ?', 'Which show or movie would you love to watch together from start to finish?'],
  ['อะไรคือสิ่งที่อีกฝ่ายทำได้เก่งจนเราแอบทึ่ง?', 'What is your partner so good at that it secretly amazes you?'],
  ['ถ้าเราเลี้ยงสัตว์ด้วยกันหนึ่งตัว อยากเลี้ยงอะไรและตั้งชื่อว่าอะไร?', 'If we raised a pet together, what would it be and what would we name it?'],
  ['สีไหนที่ทำให้นึกถึงอีกฝ่าย?', 'What color reminds you of your partner?'],
  ['ถ้ามีเวลาว่างด้วยกันหนึ่งชั่วโมงพอดี อยากทำอะไร?', 'If we had exactly one free hour together, what would you want to do?'],
  ['อาหารจานไหนที่อยากให้อีกฝ่ายลองทำให้กินสักครั้ง?', 'Which dish would you love your partner to cook for you someday?'],
  ['คำพูดติดปากของอีกฝ่ายคำไหนที่เราชอบ?', 'Which of your partner\'s catchphrases do you love?'],
  ['ถ้าได้ไปเที่ยวแบบไม่วางแผนเลย อยากให้เริ่มจากตรงไหน?', 'If we took a completely unplanned trip, where would you want to start?'],
  ['ภาพถ่ายของเราภาพไหนที่ชอบที่สุด?', 'Which photo of us do you like the most?'],
  ['ถ้าต้องเลือกหนึ่งฤดูที่เหมาะกับเรา จะเลือกฤดูไหน?', 'If you had to pick one season that suits us, which would it be?'],
  ['เกมหรือกิจกรรมอะไรที่เล่นด้วยกันแล้วสนุกที่สุด?', 'What game or activity is the most fun when we do it together?'],
  ['อะไรคือสิ่งเล็ก ๆ ที่ทำให้ยิ้มได้ทุกครั้งที่เห็นอีกฝ่ายทำ?', 'What small thing does your partner do that always makes you smile?'],
  ['ถ้าเราแต่งเพลงด้วยกัน ชื่อเพลงจะเป็นอะไร?', 'If we wrote a song together, what would its title be?'],
  ['มื้อเช้าในฝันที่อยากกินด้วยกันหน้าตาเป็นยังไง?', 'What does your dream breakfast together look like?'],
  ['ถ้าได้ใช้ชีวิตในเมืองอื่นด้วยกันหนึ่งปี อยากไปอยู่ที่ไหน?', 'If we could live in another city for a year, where would you choose?'],
  ['งานอดิเรกไหนของอีกฝ่ายที่เราอยากลองทำด้วย?', 'Which of your partner\'s hobbies would you like to try?'],
  ['อะไรคือสิ่งที่ทำให้วันธรรมดากลายเป็นวันดีได้?', 'What turns an ordinary day into a good day for you?'],
  ['ถ้าเราจัดปาร์ตี้เล็ก ๆ ด้วยกัน จะมีธีมอะไร?', 'If we threw a small party together, what would the theme be?'],
  ['ข้อความไหนจากอีกฝ่ายที่อ่านแล้วอมยิ้ม?', 'Which message from your partner made you grin?'],
  ['ถ้าได้ลองอาชีพของอีกฝ่ายหนึ่งวัน คิดว่าจะรอดไหม?', 'If you tried your partner\'s job for a day, do you think you\'d survive?'],
  ['กลิ่นไหนที่ทำให้นึกถึงอีกฝ่าย?', 'What scent reminds you of your partner?'],
  ['ถ้าเราได้รางวัลคู่รักหนึ่งรางวัล จะเป็นรางวัลสาขาอะไร?', 'If we won an award as a couple, what category would it be for?'],
  ['ชอบให้อีกฝ่ายทักทายตอนเช้าแบบไหน?', 'How do you like your partner to greet you in the morning?'],
  ['ถ้าได้เรียนอะไรใหม่ด้วยกันหนึ่งอย่าง อยากเรียนอะไร?', 'If we learned one new thing together, what would you want it to be?'],
  ['ร้านไหนที่อยากพาอีกฝ่ายไปแต่ยังไม่มีโอกาส?', 'Which place have you wanted to take your partner to but haven\'t yet?'],
  ['อะไรคือเสียงหัวเราะแบบไหนของอีกฝ่ายที่ชอบที่สุด?', 'What kind of laugh from your partner do you love the most?'],
  ['ถ้าบ้านของเรามีห้องพิเศษหนึ่งห้อง อยากให้เป็นห้องอะไร?', 'If our home had one special room, what would you want it to be?'],
  ['วันฝนตกแบบไหนที่อยากใช้เวลาด้วยกัน?', 'How would you like to spend a rainy day together?'],
  ['ถ้าต้องบรรยายเดตในฝันด้วยสามคำ จะใช้คำว่าอะไร?', 'If you described your dream date in three words, what would they be?'],
  ['เคยแอบทำอะไรน่ารัก ๆ ให้อีกฝ่ายโดยที่เขาไม่รู้บ้างไหม?', 'Have you ever done something sweet for your partner without them knowing?'],
  ['ถ้าเราเป็นคู่หูนักสืบ ใครจะเป็นคนคิดและใครจะเป็นคนลุย?', 'If we were a detective duo, who would do the thinking and who would take action?'],
  ['ตอนนี้อยากให้อีกฝ่ายทำอะไรให้มากที่สุด?', 'Right now, what would you most like your partner to do for you?'],
  ['ถ้าได้เลือกวันครบรอบใหม่ อยากฉลองแบบไหน?', 'If we could celebrate an anniversary any way we liked, how would you do it?'],
  ['สิ่งของชิ้นไหนในบ้านที่มีเรื่องราวของเราซ่อนอยู่?', 'Which object at home holds a story about us?'],
  ['ถ้าต้องอธิบายอีกฝ่ายให้คนที่ไม่รู้จักฟังในหนึ่งประโยค จะพูดว่าอะไร?', 'How would you describe your partner in one sentence to a stranger?'],
]

export const mid = [
  ['ช่วงเวลาไหนที่ทำให้รู้สึกว่ารักกันมากที่สุด?', 'When have you felt most in love with each other?'],
  ['ความทรงจำแรกที่มีต่อกันเป็นยังไง?', 'What is your first memory of each other?'],
  ['ถ้าให้บรรยายความสัมพันธ์นี้ด้วยเพลงหนึ่งเพลง จะเลือกเพลงอะไร?', 'If you had to describe this relationship with one song, which would you pick?'],
  ['อะไรที่ทำให้รู้สึกปลอดภัยเวลาอยู่ด้วยกัน?', 'What makes you feel safe when we are together?'],
  ['ความฝันที่อยากทำร่วมกันในอีก 5 ปีข้างหน้าคืออะไร?', 'What is a dream you want us to make happen in the next five years?'],
  ['ครั้งไหนที่รู้สึกภูมิใจในตัวอีกฝ่ายมากที่สุด?', 'When have you been proudest of your partner?'],
  ['อะไรคือสิ่งเล็ก ๆ ที่อยากให้อีกฝ่ายทำบ่อยขึ้น?', 'What is one small thing you wish your partner did more often?'],
  ['ถ้าย้อนกลับไปวันแรกที่เจอกัน อยากบอกอะไรกับตัวเอง?', 'If you could go back to the day we met, what would you tell yourself?'],
  ['ความรักในแบบของเราต่างจากที่เคยคิดไว้ยังไง?', 'How is our kind of love different from what you once imagined?'],
  ['อะไรที่ทำให้รู้สึกว่า "คนนี้แหละใช่"?', 'What made you feel "this is the one"?'],
  ['มีนิสัยไหนของอีกฝ่ายที่แอบชอบแต่ไม่เคยบอก?', 'Which of your partner\'s habits do you secretly love but have never mentioned?'],
  ['เวลาเหนื่อย อยากให้อีกฝ่ายดูแลยังไง?', 'When you\'re worn out, how would you like your partner to look after you?'],
  ['ความสุขเล็ก ๆ ในชีวิตประจำวันที่มีเพราะกันและกันคืออะไร?', 'What small everyday joy do you have because of each other?'],
  ['ครั้งล่าสุดที่รู้สึกซาบซึ้งในตัวอีกฝ่ายคือเมื่อไหร่?', 'When was the last time you felt truly grateful for your partner?'],
  ['อยากให้ความสัมพันธ์ของเราเติบโตไปในทิศทางไหน?', 'Which direction would you like our relationship to grow in?'],
  ['ภาษารักแบบไหนที่ทำให้รู้สึกถูกรักมากที่สุด?', 'Which love language makes you feel most loved?'],
  ['เวลาคิดถึงอีกฝ่าย มักจะนึกถึงภาพอะไร?', 'When you miss your partner, what picture comes to mind?'],
  ['สิ่งที่อยากขอบคุณอีกฝ่ายที่สุดตอนนี้คืออะไร?', 'What do you most want to thank your partner for right now?'],
  ['ถ้าต้องเขียนจดหมายถึงกันในอีก 10 ปี อยากเขียนว่าอะไร?', 'If you wrote each other a letter to open in ten years, what would it say?'],
  ['อะไรที่ทำให้เราหัวเราะด้วยกันได้เสมอ?', 'What always makes us laugh together?'],
  ['มีความฝันส่วนตัวข้อไหนที่อยากให้อีกฝ่ายช่วยสนับสนุน?', 'Which of your personal dreams would you like your partner to support?'],
  ['วันธรรมดา ๆ แบบไหนที่ทำให้รู้สึกว่ามีความสุขที่สุด?', 'What kind of ordinary day makes you happiest?'],
  ['เวลาที่เงียบอยู่ด้วยกัน รู้สึกยังไง?', 'How do you feel when we are quiet together?'],
  ['ถ้าให้เลือกหนึ่งสิ่งที่อยากทำให้อีกฝ่ายมีความสุขวันนี้ จะทำอะไร?', 'If you could do one thing to make your partner happy today, what would it be?'],
  ['ช่วงไหนของความสัมพันธ์ที่รู้สึกว่าเราใกล้กันขึ้นมาก?', 'At what point in our relationship did we grow much closer?'],
  ['อะไรที่ได้เรียนรู้เกี่ยวกับตัวเองตั้งแต่คบกัน?', 'What have you learned about yourself since we got together?'],
  ['ธรรมเนียมเล็ก ๆ ของเราสองคนที่อยากรักษาไว้คืออะไร?', 'Which little tradition of ours do you want to keep?'],
  ['เคยมีช่วงไหนที่รู้สึกว่าอีกฝ่ายเข้าใจเราโดยไม่ต้องพูด?', 'Was there a moment your partner understood you without a word?'],
  ['ความสัมพันธ์ในฝันที่เคยเห็นจากคนรอบตัวเป็นแบบไหน?', 'What relationship around you have you looked up to, and why?'],
  ['อะไรที่ทำให้รู้สึกว่าอีกฝ่ายใส่ใจเราจริง ๆ?', 'What makes you feel your partner truly cares about you?'],
  ['วันที่แย่ที่สุดของเรา อีกฝ่ายช่วยให้ดีขึ้นยังไง?', 'On your worst day, how did your partner help make it better?'],
  ['อยากให้บ้านของเราในอนาคตมีบรรยากาศแบบไหน?', 'What kind of atmosphere do you want our future home to have?'],
  ['การทะเลาะครั้งไหนที่ทำให้เราเข้าใจกันมากขึ้น?', 'Which argument ended up helping us understand each other better?'],
  ['คำชมแบบไหนจากอีกฝ่ายที่ทำให้ใจฟู?', 'What kind of compliment from your partner makes your heart full?'],
  ['ถ้าต้องเลือกสามคำที่อธิบายความสัมพันธ์ของเราตอนนี้ จะเลือกคำว่าอะไร?', 'Which three words describe our relationship right now?'],
  ['เป้าหมายอะไรที่อยากทำให้สำเร็จด้วยกันในปีนี้?', 'What goal do you want us to achieve together this year?'],
  ['เรื่องเงินในแบบที่สบายใจสำหรับเราสองคนควรเป็นยังไง?', 'What would a comfortable way of handling money look like for us?'],
  ['อยากใช้วันเกิดปีหน้าของตัวเองแบบไหน?', 'How would you like to spend your next birthday?'],
  ['ครอบครัวของอีกฝ่ายสอนอะไรเราบ้าง?', 'What has your partner\'s family taught you?'],
  ['เพื่อนของอีกฝ่ายทำให้เรารู้จักอีกฝ่ายในมุมไหนเพิ่มขึ้น?', 'What side of your partner did you discover through their friends?'],
  ['ถ้าเราต้องย้ายบ้าน อะไรคือสิ่งที่ต้องมีในบ้านใหม่?', 'If we moved, what would our new home absolutely need?'],
  ['เวลาไม่ได้เจอกันนาน ๆ อะไรที่ทำให้รู้สึกยังเชื่อมกันอยู่?', 'When we\'re apart for a while, what keeps you feeling connected?'],
  ['ชอบตัวเองตอนอยู่กับอีกฝ่ายในเรื่องไหน?', 'What do you like about who you are when you\'re with your partner?'],
  ['มีเรื่องไหนที่อยากให้เราลองทำใหม่ด้วยกันเดือนนี้?', 'What would you like us to try together for the first time this month?'],
  ['ความทรงจำการเดินทางด้วยกันครั้งไหนที่ยังนึกถึงบ่อย?', 'Which trip together do you still think about often?'],
  ['อะไรที่อีกฝ่ายทำแล้วทำให้รู้สึกว่าเป็นทีมเดียวกัน?', 'What does your partner do that makes you feel like a team?'],
  ['อยากให้เราดูแลสุขภาพด้วยกันแบบไหน?', 'How would you like us to take care of our health together?'],
  ['ถ้าได้หยุดเวลาไว้หนึ่งช่วงของเรา จะเลือกช่วงไหน?', 'If you could freeze one moment of ours, which would it be?'],
  ['คิดว่าเพื่อนสนิทของเรามองความสัมพันธ์นี้ว่ายังไง?', 'How do you think your close friends see our relationship?'],
  ['ความเปลี่ยนแปลงไหนในตัวอีกฝ่ายที่ประทับใจ?', 'Which change in your partner has impressed you?'],
  ['อยากให้ช่วงเย็นหลังเลิกงานของเราเป็นแบบไหน?', 'What would you like our evenings after work to look like?'],
  ['มีความเชื่อเรื่องความรักข้อไหนที่เปลี่ยนไปเพราะความสัมพันธ์นี้?', 'Which belief about love has changed because of this relationship?'],
  ['เวลาเราทำงานบ้านด้วยกัน อยากแบ่งหน้าที่แบบไหน?', 'How would you like us to share chores at home?'],
  ['อะไรคือเรื่องที่อยากชวนอีกฝ่ายคุยแต่ยังไม่มีจังหวะ?', 'What topic have you wanted to bring up but haven\'t found the right moment for?'],
  ['ช่วงเวลาไหนที่รู้สึกว่าอีกฝ่ายเชื่อมั่นในตัวเรา?', 'When did you feel your partner truly believed in you?'],
  ['ถ้าเราแก่ไปด้วยกัน อยากให้วันธรรมดาของเราเป็นยังไง?', 'If we grow old together, what would you want an ordinary day to look like?'],
  ['มีเพลงหรือหนังเรื่องไหนที่ทำให้เข้าใจความรักในแบบของเรามากขึ้น?', 'Is there a song or film that helped you understand our kind of love?'],
  ['อะไรที่อยากให้เราทำต่อไปแม้จะคบกันนานแล้ว?', 'What do you want us to keep doing no matter how long we\'re together?'],
  ['มีคำสัญญาเล็ก ๆ อะไรที่อยากให้เราสัญญากัน?', 'What small promise would you like us to make to each other?'],
  ['ชอบให้อีกฝ่ายปลอบใจด้วยคำพูดหรือด้วยการกระทำ?', 'Do you prefer your partner to comfort you with words or with actions?'],
  ['ความแตกต่างของเราสองคนข้อไหนที่กลับทำให้เราลงตัว?', 'Which of our differences actually makes us work well together?'],
  ['มีวันไหนที่อยากให้ทั้งโลกรู้ว่าเรามีความสุขแค่ไหน?', 'Was there a day you wanted the whole world to know how happy we were?'],
  ['เรื่องไหนที่อีกฝ่ายสอนให้เรามองโลกต่างไป?', 'What has your partner taught you to see differently?'],
  ['ถ้าได้ทำโปรเจกต์ด้วยกันหนึ่งอย่าง อยากทำอะไร?', 'If we took on one project together, what would you want it to be?'],
  ['ช่วงที่งานยุ่ง อยากให้เราดูแลความสัมพันธ์กันแบบไหน?', 'When life gets busy, how would you like us to look after our relationship?'],
  ['อะไรที่อยากให้อีกฝ่ายรู้เกี่ยวกับวันที่เราเงียบไป?', 'What do you want your partner to know about the days you go quiet?'],
  ['ความสำเร็จไหนของอีกฝ่ายที่อยากฉลองให้ใหญ่กว่านี้?', 'Which of your partner\'s achievements deserved a bigger celebration?'],
  ['เคยรู้สึกว่าอีกฝ่ายเป็นบ้านของเราตอนไหน?', 'When have you felt that your partner is your home?'],
  ['อยากให้เราจัดการกับความเครียดด้วยกันแบบไหน?', 'How would you like us to handle stress together?'],
  ['เรื่องเล็ก ๆ ที่อีกฝ่ายจำได้แล้วทำให้ซึ้งคืออะไร?', 'What small detail did your partner remember that touched you?'],
  ['ถ้าเราจะมีคติประจำคู่ จะเป็นประโยคว่าอะไร?', 'If we had a couple\'s motto, what would it be?'],
  ['ความสัมพันธ์ของเราสอนเรื่องความอดทนยังไงบ้าง?', 'What has our relationship taught you about patience?'],
  ['อยากเห็นตัวเราสองคนเป็นแบบไหนในอีก 10 ปี?', 'How do you picture the two of us in ten years?'],
  ['มีมุมไหนของอีกฝ่ายที่คนอื่นไม่ค่อยเห็นแต่เราเห็น?', 'What side of your partner do you see that others rarely do?'],
  ['ชอบให้เราขอโทษกันแบบไหน?', 'How do you like us to apologize to each other?'],
  ['เวลาไหนที่รู้สึกว่าเราสองคนเติบโตไปด้วยกัน?', 'When have you felt us growing together?'],
  ['อะไรที่ทำให้ไว้ใจอีกฝ่ายมากขึ้นเรื่อย ๆ?', 'What has made you trust your partner more and more?'],
  ['อยากให้เราใช้เวลากับเพื่อนและครอบครัวของแต่ละฝ่ายแบบไหน?', 'How would you like us to balance time with each other\'s friends and family?'],
  ['ช่วงเวลาไหนที่รู้สึกว่าเรารับมือกับปัญหาได้ดีด้วยกัน?', 'When did we handle a problem really well together?'],
  ['มีของขวัญที่ไม่ใช่สิ่งของอะไรที่อยากได้จากอีกฝ่าย?', 'What non-material gift would you love to receive from your partner?'],
  ['อยากให้เราใช้โทรศัพท์ตอนอยู่ด้วยกันน้อยลงไหม และอยากทำอะไรแทน?', 'Would you like us to use our phones less together, and what would we do instead?'],
  ['มีเรื่องอะไรที่ภูมิใจในตัวเองตั้งแต่คบกันมา?', 'What are you proud of yourself for since we\'ve been together?'],
  ['การได้อยู่กับอีกฝ่ายเปลี่ยนวิธีที่เรามองอนาคตยังไง?', 'How has being with your partner changed how you see the future?'],
  ['เคยมีช่วงไหนที่รู้สึกห่างกัน แล้วอะไรทำให้กลับมาใกล้กัน?', 'Was there a time we drifted apart, and what brought us back?'],
  ['ชอบโมเมนต์แบบไหนมากกว่ากัน ระหว่างเดตพิเศษหรือวันสบาย ๆ ที่บ้าน?', 'Which do you love more: special dates or easy days at home?'],
  ['ช่วงไหนของปีที่รู้สึกว่าเป็นช่วงของเรา?', 'Which part of the year feels like "our" time?'],
  ['สิ่งที่อีกฝ่ายทำเพื่อเราแล้วเราอาจยังไม่ได้ขอบคุณคืออะไร?', 'What has your partner done for you that you may never have thanked them for?'],
  ['อยากให้เราเรียนรู้กันและกันมากขึ้นในเรื่องไหน?', 'In what area would you like us to get to know each other better?'],
  ['ช่วงที่ป่วย อยากให้อีกฝ่ายดูแลยังไง?', 'When you\'re sick, how would you like your partner to care for you?'],
  ['อะไรที่ทำให้รู้สึกว่าเรายังตื่นเต้นกับกันและกันอยู่?', 'What keeps us excited about each other?'],
  ['ถ้าเราจะเขียนหนังสือเรื่องความรักของเรา บทแรกจะชื่อว่าอะไร?', 'If we wrote a book about our love, what would the first chapter be called?'],
  ['มีเรื่องอะไรที่อยากให้เราตัดสินใจด้วยกันมากขึ้น?', 'What decisions would you like us to make together more often?'],
  ['เคยเห็นอีกฝ่ายกล้าหาญตอนไหน?', 'When have you seen your partner be brave?'],
  ['มีเรื่องอะไรที่อยากให้เราหัวเราะเยาะตัวเองได้มากขึ้น?', 'What would you like us to laugh at ourselves about more?'],
  ['อะไรที่ทำให้รู้สึกว่าความสัมพันธ์นี้คุ้มค่ากับความพยายาม?', 'What makes this relationship worth the effort to you?'],
  ['อยากให้เราฉลองความสำเร็จเล็ก ๆ ของกันและกันยังไง?', 'How would you like us to celebrate each other\'s small wins?'],
  ['ความสัมพันธ์นี้ทำให้รู้สึกเป็นตัวเองมากขึ้นหรือน้อยลง เพราะอะไร?', 'Does this relationship make you feel more or less like yourself, and why?'],
  ['มีความทรงจำไหนที่อยากสร้างด้วยกันก่อนสิ้นปีนี้?', 'What memory would you like us to create before the end of this year?'],
  ['อะไรคือสิ่งที่อยากให้อีกฝ่ายจำเกี่ยวกับเราไว้เสมอ?', 'What do you want your partner to always remember about you?'],
  ['ถ้าวันหนึ่งเราต้องห่างกันไกล อยากให้เรารักษาความสัมพันธ์แบบไหน?', 'If we ever had to live far apart, how would you want us to keep things strong?'],
]

export const deep = [
  ['มีเรื่องไหนที่อยากบอกกันมานานแต่ยังไม่เคยพูด?', 'Is there something you\'ve wanted to tell your partner for a long time but never said?'],
  ['เวลาทะเลาะกัน อยากให้อีกฝ่ายเข้าใจอะไรเกี่ยวกับเรา?', 'When we argue, what do you wish your partner understood about you?'],
  ['อะไรคือสิ่งที่กลัวที่สุดในความสัมพันธ์นี้?', 'What do you fear most in this relationship?'],
  ['มีเรื่องอะไรของตัวเองที่ยังไม่กล้าเปิดใจให้ฟังทั้งหมด?', 'Is there something about yourself you haven\'t dared to fully open up about yet?'],
  ['ความเชื่อใจสำหรับเราหมายถึงอะไร?', 'What does trust mean to you?'],
  ['มีช่วงเวลาไหนที่เกือบยอมแพ้ แต่ก็ผ่านมาได้เพราะอะไร?', 'Was there a time we almost gave up? What got us through it?'],
  ['ความรู้สึกไหนที่อยากแบ่งปันกันมากขึ้น?', 'Which feelings would you like us to share with each other more?'],
  ['อยากถูกจดจำในความสัมพันธ์นี้ว่าเป็นคนแบบไหน?', 'What kind of person do you want to be remembered as in this relationship?'],
  ['อะไรคือสิ่งที่เรียนรู้เกี่ยวกับความรักจากความสัมพันธ์นี้?', 'What has this relationship taught you about love?'],
  ['อะไรที่เราทำได้ดีขึ้นในฐานะคนรักของกันและกัน?', 'What could we each do better as partners to each other?'],
  ['ตอนเด็ก ๆ เห็นความรักของผู้ใหญ่รอบตัวเป็นแบบไหน และมันส่งผลกับเราตอนนี้ยังไง?', 'What did love look like between the adults around you growing up, and how does it affect you now?'],
  ['เวลารู้สึกไม่มั่นคงในความสัมพันธ์ มักแสดงออกมาแบบไหน?', 'When you feel insecure in the relationship, how does it usually show?'],
  ['อะไรที่ทำให้รู้สึกว่าไม่ได้รับความรักพอ แม้อีกฝ่ายอาจไม่ได้ตั้งใจ?', 'What makes you feel unloved, even when your partner doesn\'t mean it?'],
  ['มีบาดแผลจากความสัมพันธ์เก่าที่ยังส่งผลกับเราอยู่ไหม?', 'Is there a hurt from a past relationship that still affects you?'],
  ['เวลาโกรธ จริง ๆ แล้วข้างใต้ความโกรธนั้นมักเป็นความรู้สึกอะไร?', 'When you\'re angry, what feeling is usually underneath it?'],
  ['ต้องการพื้นที่ส่วนตัวแค่ไหน และอยากให้อีกฝ่ายเข้าใจเรื่องนี้ยังไง?', 'How much personal space do you need, and how would you like your partner to understand that?'],
  ['มีความต้องการไหนที่รู้สึกผิดที่จะขอจากอีกฝ่าย?', 'Is there a need you feel guilty asking your partner for?'],
  ['อะไรคือสิ่งที่กลัวว่าอีกฝ่ายจะรู้แล้วรักเราน้อยลง?', 'What are you afraid your partner would love you less for if they knew?'],
  ['เวลาเราทะเลาะกัน มักจะหนี ปะทะ หรือเงียบ และเพราะอะไร?', 'When we argue, do you tend to withdraw, fight back, or go quiet, and why?'],
  ['อะไรที่ทำให้รู้สึกว่าถูกมองเห็นจริง ๆ ในความสัมพันธ์นี้?', 'What makes you feel truly seen in this relationship?'],
  ['มีความคาดหวังไหนที่ยังไม่เคยพูดออกมาแต่หวังว่าอีกฝ่ายจะเดาได้?', 'Is there an expectation you\'ve never voiced but hope your partner will guess?'],
  ['การให้อภัยสำหรับเรายากหรือง่าย และขึ้นอยู่กับอะไร?', 'Is forgiving hard or easy for you, and what does it depend on?'],
  ['เวลาอีกฝ่ายผิดหวังในตัวเรา เรารู้สึกยังไงข้างใน?', 'How do you feel inside when your partner is disappointed in you?'],
  ['มีส่วนไหนของตัวเองที่ยังพยายามยอมรับอยู่?', 'Which part of yourself are you still learning to accept?'],
  ['ความรักควรเปลี่ยนเราหรือยอมรับเราอย่างที่เป็น หรือทั้งสองอย่าง?', 'Should love change us, accept us as we are, or both?'],
  ['มีช่วงไหนที่รู้สึกเหงาแม้อยู่ด้วยกัน?', 'Have you ever felt lonely even when we were together?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องพิสูจน์ตัวเองกับอีกฝ่าย?', 'What makes you feel you have to prove yourself to your partner?'],
  ['เรามีวิธีเรียกร้องความสนใจแบบไหนที่อาจไม่รู้ตัว?', 'How might you be asking for attention without realizing it?'],
  ['ความหึงหวงสำหรับเราหมายถึงอะไร และมันมาจากไหน?', 'What does jealousy mean to you, and where does it come from?'],
  ['มีคำพูดไหนที่อีกฝ่ายเคยพูดแล้วยังติดอยู่ในใจ?', 'Is there something your partner once said that still stays with you?'],
  ['อะไรคือสิ่งที่ต้องการมากที่สุดตอนที่กำลังเศร้า?', 'What do you need most when you\'re sad?'],
  ['เวลาเครียด เราเปลี่ยนไปเป็นคนแบบไหน และอยากให้อีกฝ่ายรับมือยังไง?', 'Who do you become when you\'re stressed, and how would you like your partner to respond?'],
  ['ความสัมพันธ์นี้เติมเต็มส่วนไหนในตัวเราที่เคยขาดหายไป?', 'What part of you that used to feel missing does this relationship fill?'],
  ['มีความฝันไหนที่ยอมเก็บไว้เพื่อความสัมพันธ์ และรู้สึกกับมันยังไง?', 'Is there a dream you put aside for the relationship, and how do you feel about it?'],
  ['ถ้าเราสองคนเลิกกัน คิดว่าเหตุผลจะเป็นอะไร และเราป้องกันได้ยังไง?', 'If we ever broke up, what would the reason be, and how could we prevent it?'],
  ['อะไรคือสิ่งที่ไม่เคยยอมแลกได้ในความสัมพันธ์?', 'What would you never compromise on in a relationship?'],
  ['รู้สึกว่าตัวเองคู่ควรกับความรักแบบที่ได้รับอยู่ไหม?', 'Do you feel you deserve the love you\'re receiving?'],
  ['มีเรื่องไหนที่ยังรู้สึกผิดต่ออีกฝ่ายอยู่?', 'Is there something you still feel guilty about toward your partner?'],
  ['ความใกล้ชิดทางใจสำหรับเราหน้าตาเป็นยังไง?', 'What does emotional closeness look like to you?'],
  ['อะไรที่ทำให้เราปิดใจไม่อยากคุยต่อ?', 'What makes you shut down and stop wanting to talk?'],
  ['เวลาไหนที่รู้สึกว่าต้องเป็นคนเข้มแข็งตลอดเวลา และเหนื่อยไหม?', 'When do you feel you have to be the strong one, and does it wear you out?'],
  ['อยากให้อีกฝ่ายถามเราเรื่องอะไรบ่อยขึ้น?', 'What would you like your partner to ask you about more often?'],
  ['มีความทรงจำในวัยเด็กไหนที่อยากให้อีกฝ่ายรู้เพื่อเข้าใจเรามากขึ้น?', 'Which childhood memory would help your partner understand you better?'],
  ['เราเรียนรู้วิธีรักคนอื่นมาจากใคร?', 'Who taught you how to love?'],
  ['อะไรคือสิ่งที่อยากเปลี่ยนในตัวเองเพื่อให้ความสัมพันธ์นี้ดีขึ้น?', 'What would you like to change in yourself to make this relationship better?'],
  ['เคยรู้สึกว่าต้องซ่อนบางส่วนของตัวเองไว้จากอีกฝ่ายไหม?', 'Have you ever felt you had to hide part of yourself from your partner?'],
  ['ความผิดพลาดไหนในอดีตที่ทำให้เรากลายเป็นคนรักที่ดีขึ้น?', 'Which past mistake made you a better partner?'],
  ['อะไรที่ทำให้กลัวการถูกทิ้ง และเรารับมือกับมันยังไง?', 'What makes you afraid of being left, and how do you cope with it?'],
  ['อะไรที่ทำให้รู้สึกอึดอัดเวลาได้รับความรักมากเกินไป?', 'What makes you uncomfortable when you receive a lot of love?'],
  ['ตอนนี้ความสัมพันธ์ของเราขาดอะไรไปหนึ่งอย่าง?', 'If our relationship is missing one thing right now, what is it?'],
  ['มีขอบเขตไหนที่อยากให้อีกฝ่ายเคารพมากขึ้น?', 'Which boundary would you like your partner to respect more?'],
  ['เวลาถูกวิจารณ์ แม้จะหวังดี เรารู้สึกยังไง?', 'How do you feel when you\'re criticized, even with good intentions?'],
  ['อะไรคือความเชื่อเกี่ยวกับตัวเองที่ทำให้รักได้ยาก?', 'What belief about yourself makes it hard to love or be loved?'],
  ['เคยรู้สึกว่าความสัมพันธ์นี้เป็นภาระไหม และตอนนั้นเกิดอะไรขึ้น?', 'Have you ever felt this relationship was a burden, and what was happening then?'],
  ['ถ้าอีกฝ่ายเปลี่ยนไปมาก เรายังจะรักเขาอยู่ไหม เพราะอะไร?', 'If your partner changed a lot, would you still love them, and why?'],
  ['อะไรที่ทำให้รู้สึกว่าความต้องการของเราสำคัญน้อยกว่าของอีกฝ่าย?', 'What makes you feel your needs matter less than your partner\'s?'],
  ['มีเรื่องอะไรที่อยากให้อีกฝ่ายรู้ว่า "ไม่ใช่ความผิดของคุณ"?', 'Is there something you want your partner to know is "not your fault"?'],
  ['ความเปราะบางที่สุดของเราคืออะไร?', 'What is your most vulnerable side?'],
  ['เวลาอีกฝ่ายเงียบ เรามักจะคิดไปเองว่าอะไร?', 'When your partner goes quiet, what do you tend to assume?'],
  ['อะไรที่ทำให้อยากปกป้องอีกฝ่ายจนบางทีอาจมากเกินไป?', 'What makes you want to protect your partner, maybe a little too much?'],
  ['ความสุขของเราขึ้นอยู่กับอีกฝ่ายมากแค่ไหน และรู้สึกยังไงกับเรื่องนี้?', 'How much does your happiness depend on your partner, and how do you feel about that?'],
  ['มีเรื่องไหนที่ไม่เคยให้อภัยตัวเองในความสัมพันธ์นี้?', 'Is there something in this relationship you\'ve never forgiven yourself for?'],
  ['อยากให้ความรักของเราแตกต่างจากความรักที่เคยเห็นมาอย่างไร?', 'How do you want our love to be different from the love you grew up seeing?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องควบคุมสถานการณ์?', 'What makes you feel you need to be in control?'],
  ['รู้สึกปลอดภัยพอที่จะร้องไห้ต่อหน้าอีกฝ่ายไหม?', 'Do you feel safe enough to cry in front of your partner?'],
  ['ความกลัวที่ใหญ่ที่สุดเกี่ยวกับอนาคตของเราคืออะไร?', 'What is your biggest fear about our future?'],
  ['ช่วงไหนที่รู้สึกว่าเรารักอีกฝ่ายมากกว่าที่อีกฝ่ายรักเรา?', 'Have you ever felt you loved your partner more than they loved you?'],
  ['ความคาดหวังจากครอบครัวเรื่องความรักกดดันเราแค่ไหน?', 'How much pressure do you feel from your family\'s expectations about love?'],
  ['อะไรที่ทำให้กลับมาเชื่อใจอีกครั้งหลังจากผิดหวัง?', 'What helps you trust again after being let down?'],
  ['เคยรักตัวเองน้อยลงเพราะความสัมพันธ์ไหนไหม?', 'Has any relationship ever made you love yourself less?'],
  ['ความเหงาแบบไหนที่ความรักเติมไม่เต็ม?', 'What kind of loneliness can love not fill?'],
  ['มีเรื่องอะไรที่เราพูดว่า "ไม่เป็นไร" แต่จริง ๆ แล้วเป็น?', 'What do you say "it\'s fine" about when it really isn\'t?'],
  ['อะไรคือสิ่งที่อยากได้ยินจากอีกฝ่ายมากที่สุดในวันที่แย่?', 'What do you most want to hear from your partner on a bad day?'],
  ['เวลาขัดแย้ง เราต้องการเหตุผลหรือความเข้าใจก่อน?', 'In a conflict, do you need logic or understanding first?'],
  ['ความรักทำให้เรากลัวอะไรมากขึ้นบ้าง?', 'What has love made you more afraid of?'],
  ['มีความโกรธเก่า ๆ ที่ยังไม่ได้ปล่อยวางไหม?', 'Is there an old anger you haven\'t let go of yet?'],
  ['อะไรที่ทำให้รู้สึกว่าเราเป็นภาระของอีกฝ่าย?', 'What makes you feel like a burden to your partner?'],
  ['เราแสดงความรักแบบที่อยากได้รับ หรือแบบที่อีกฝ่ายต้องการ?', 'Do you show love the way you want to receive it, or the way your partner needs it?'],
  ['ความสัมพันธ์นี้เผยให้เห็นด้านไหนของเราที่ไม่ค่อยชอบ?', 'What side of yourself that you don\'t love has this relationship revealed?'],
  ['ถ้าต้องอธิบายวิธีที่เราผูกพันกับคนอื่น จะอธิบายว่ายังไง?', 'How would you describe the way you attach to people?'],
  ['เคยรู้สึกว่าไม่ดีพอสำหรับอีกฝ่ายไหม และอะไรทำให้รู้สึกแบบนั้น?', 'Have you ever felt not good enough for your partner, and what caused it?'],
  ['มีความต้องการทางใจอะไรที่ไม่เคยได้รับตอนเด็ก แล้วหวังให้ได้จากความรัก?', 'Is there an emotional need you didn\'t get as a child that you hope love will meet?'],
  ['เวลาเราขอโทษ ยากตรงไหนที่สุด?', 'What is the hardest part of apologizing for you?'],
  ['อยากให้อีกฝ่ายอดทนกับเราในเรื่องไหนมากขึ้น?', 'Where would you like your partner to be more patient with you?'],
  ['อะไรคือรูปแบบซ้ำ ๆ ที่เห็นในความสัมพันธ์ทุกครั้งของเรา?', 'What pattern do you notice repeating in all your relationships?'],
  ['การเป็นตัวของตัวเองกับการเป็นคู่กัน อะไรยากกว่าสำหรับเรา?', 'Which is harder for you: being yourself or being part of a couple?'],
  ['อะไรที่ทำให้ใจเราอ่อนลงทันทีแม้กำลังโกรธอยู่?', 'What softens your heart instantly, even when you\'re angry?'],
  ['มีคำถามไหนที่กลัวจะถามอีกฝ่ายเพราะกลัวคำตอบ?', 'Is there a question you\'re afraid to ask your partner because of the answer?'],
  ['อะไรที่ทำให้รู้สึกว่าความรักนี้มั่นคง?', 'What makes this love feel steady to you?'],
  ['เราใช้ความยุ่งหรืองานเป็นที่หลบจากความรู้สึกบ้างไหม?', 'Do you ever use busyness or work to hide from your feelings?'],
  ['เคยรู้สึกว่าอีกฝ่ายไม่ฟังจริง ๆ ตอนไหน และตอนนั้นต้องการอะไร?', 'When did you feel your partner wasn\'t really listening, and what did you need?'],
  ['ความสัมพันธ์นี้รักษาแผลใจเก่าของเราได้บ้างไหม?', 'Has this relationship helped heal an old wound of yours?'],
  ['อะไรคือความกลัวที่ทำให้ไม่กล้าขอสิ่งที่ต้องการ?', 'What fear stops you from asking for what you want?'],
  ['รู้สึกยังไงกับการพึ่งพาอีกฝ่าย?', 'How do you feel about depending on your partner?'],
  ['อะไรที่ทำให้อยากหนีเวลาความสัมพันธ์ลึกซึ้งขึ้น?', 'What makes you want to pull away as things get deeper?'],
  ['ความรักแบบไหนที่เคยคิดว่าตัวเองไม่มีวันได้รับ?', 'What kind of love did you once think you\'d never get?'],
  ['ถ้าอีกฝ่ายอ่านใจเราได้หนึ่งวัน กลัวเขาจะเห็นอะไร?', 'If your partner could read your mind for a day, what would you fear they\'d see?'],
  ['อะไรที่ยังไม่แน่ใจเกี่ยวกับอนาคตของเรา?', 'What are you still unsure about in our future?'],
  ['การได้รับคำชมทำให้รู้สึกดีหรือเขิน และเพราะอะไร?', 'Do compliments make you feel good or awkward, and why?'],
  ['เคยเปรียบเทียบความสัมพันธ์ของเรากับของคนอื่นไหม และรู้สึกยังไง?', 'Do you ever compare our relationship to others, and how does it make you feel?'],
  ['อะไรที่ทำให้รู้สึกว่าถูกเข้าใจผิดบ่อยที่สุด?', 'What do you feel most often misunderstood about?'],
  ['ความกลัวการผูกมัดเคยเกิดขึ้นกับเราไหม?', 'Have you ever been afraid of commitment?'],
  ['มีเรื่องอะไรที่ยังเสียใจว่าไม่ได้ทำให้อีกฝ่าย?', 'Is there something you regret not doing for your partner?'],
  ['ความรักที่ดีควรรู้สึกยังไงในร่างกายของเรา?', 'How should good love feel in your body?'],
  ['อะไรทำให้รู้สึกว่ามีคุณค่าที่ไม่เกี่ยวกับความสัมพันธ์?', 'What makes you feel worthy, apart from the relationship?'],
  ['ถ้าความสัมพันธ์นี้เป็นครู มันกำลังสอนบทเรียนอะไรเราอยู่?', 'If this relationship were a teacher, what lesson is it teaching you right now?'],
  ['มีเรื่องที่ยังไม่พร้อมจะพูด แต่อยากให้อีกฝ่ายรู้ว่ามีอยู่ไหม?', 'Is there something you\'re not ready to talk about but want your partner to know exists?'],
  ['เวลาไหนที่รู้สึกว่าความรักของเราถูกทดสอบมากที่สุด?', 'When has our love been tested the most?'],
  ['อยากให้อีกฝ่ายเห็นความพยายามไหนของเราที่อาจมองไม่เห็น?', 'Which of your efforts would you like your partner to notice?'],
  ['ความสัมพันธ์ที่ดีต่อใจกับความสัมพันธ์ที่ตื่นเต้น ต่างกันยังไงสำหรับเรา?', 'What\'s the difference for you between a relationship that feels good and one that feels exciting?'],
  ['รู้สึกว่าต้องเป็นคนที่ "ง่าย" ตลอดเวลาเพื่อให้ถูกรักไหม?', 'Do you feel you have to be "easy" all the time to be loved?'],
  ['อะไรที่ทำให้กลัวว่าความสุขจะอยู่ไม่นาน?', 'What makes you fear that happiness won\'t last?'],
  ['การยอมให้กันกับการเสียตัวตน เส้นแบ่งอยู่ตรงไหนสำหรับเรา?', 'Where is the line for you between compromising and losing yourself?'],
  ['มีความรู้สึกไหนที่ไม่เคยมีคำเรียก แต่รู้สึกกับอีกฝ่ายบ่อย ๆ?', 'Is there a feeling you have for your partner that you\'ve never had a word for?'],
  ['อะไรที่เราต้องการจากความสัมพันธ์ แต่ยังไม่กล้ายอมรับกับตัวเอง?', 'What do you need from this relationship that you haven\'t admitted to yourself?'],
  ['เคยรู้สึกว่าเราดูแลอีกฝ่ายมากกว่าดูแลตัวเองไหม?', 'Have you ever cared for your partner more than for yourself?'],
  ['อะไรที่ทำให้รู้สึกปลอดภัยพอที่จะพูดความจริงที่ยาก?', 'What makes you feel safe enough to say a hard truth?'],
  ['ความรักทำให้เรากล้าขึ้นในเรื่องไหนบ้าง?', 'In what ways has love made you braver?'],
  ['มีความทรงจำที่เจ็บแต่ทำให้เราเติบโตด้วยกันไหม?', 'Is there a painful memory that helped us grow together?'],
  ['เวลาอีกฝ่ายประสบความสำเร็จ มีความรู้สึกอื่นปนนอกจากดีใจไหม?', 'When your partner succeeds, do you ever feel anything besides happiness?'],
  ['อะไรที่ยังไม่เข้าใจในตัวอีกฝ่ายแม้จะคบกันมานาน?', 'What do you still not understand about your partner, even after all this time?'],
  ['ความสัมพันธ์นี้ทำให้เรามองครอบครัวของตัวเองต่างไปยังไง?', 'How has this relationship changed the way you see your own family?'],
  ['มีความเชื่อเรื่องตัวเองแบบไหนที่อีกฝ่ายช่วยเปลี่ยน?', 'Which belief about yourself has your partner helped change?'],
  ['อะไรคือความสุขที่กลัวจะเสียไปที่สุด?', 'What happiness are you most afraid of losing?'],
  ['เวลาไม่แน่ใจในความรู้สึกของอีกฝ่าย เราทำอะไร?', 'What do you do when you\'re unsure how your partner feels?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเก็บความรู้สึกไว้คนเดียว?', 'What makes you feel you have to keep your feelings to yourself?'],
  ['อยากให้ความรักของเราทิ้งอะไรไว้ให้โลกนี้?', 'What would you want our love to leave behind in the world?'],
  ['มีช่วงไหนที่เรารักตัวเองมากขึ้นเพราะอีกฝ่าย?', 'When did your partner help you love yourself more?'],
  ['การปล่อยให้อีกฝ่ายดูแลเรายากไหม เพราะอะไร?', 'Is it hard to let your partner take care of you, and why?'],
  ['ถ้าต้องบอกความกลัวหนึ่งอย่างที่ไม่เคยบอกใคร จะเป็นเรื่องอะไร?', 'If you shared one fear you\'ve never told anyone, what would it be?'],
  ['อะไรที่ทำให้รู้สึกว่ายังไม่พร้อมสำหรับก้าวต่อไปของความสัมพันธ์?', 'What makes you feel not ready for the next step in our relationship?'],
  ['เราเป็นคนที่ต้องการความชัดเจนหรือรับความไม่แน่นอนได้ในความรัก?', 'In love, do you need clarity, or can you live with uncertainty?'],
  ['มีความรู้สึกผิดหวังเล็ก ๆ ที่สะสมไว้และยังไม่ได้พูดไหม?', 'Are there small disappointments you\'ve been holding onto without saying?'],
  ['อะไรที่ทำให้รู้สึกว่าความสัมพันธ์นี้แตกต่างจากทุกครั้งที่ผ่านมา?', 'What makes this relationship different from every one before it?'],
  ['เคยคิดว่าความรักต้องเจ็บถึงจะจริงไหม และตอนนี้คิดยังไง?', 'Did you ever believe love has to hurt to be real, and what do you think now?'],
  ['มีความต้องการไหนที่เพิ่งรู้ตัวว่ามีหลังจากคบกัน?', 'Which need did you only discover after we got together?'],
  ['อะไรที่ทำให้รู้สึกว่าเรากำลังเล่นบทบาทแทนที่จะเป็นตัวเอง?', 'What makes you feel you\'re playing a role instead of being yourself?'],
  ['เวลาอีกฝ่ายต้องการเรามาก เรารู้สึกอบอุ่นหรือหนักใจ?', 'When your partner needs you a lot, do you feel warmth or weight?'],
  ['ความรักทำให้เรามองความตายหรือการสูญเสียต่างไปไหม?', 'Has love changed the way you think about loss?'],
  ['ถ้าเลือกได้ อยากเยียวยาความรู้สึกไหนในตัวเองก่อน?', 'If you could heal one feeling in yourself first, which would it be?'],
  ['อะไรที่เราทำเพื่อเอาใจอีกฝ่ายจนลืมถามตัวเองว่าอยากทำไหม?', 'What do you do to please your partner without asking whether you want to?'],
  ['การถูกปฏิเสธจากอีกฝ่ายแม้เรื่องเล็ก ๆ ส่งผลกับเราแค่ไหน?', 'How much does being turned down by your partner, even in small things, affect you?'],
  ['มีภาพจำในวัยเด็กเรื่องการทะเลาะของผู้ใหญ่ที่ยังติดอยู่ไหม?', 'Is there a childhood memory of adults arguing that still stays with you?'],
  ['อยากให้อีกฝ่ายรู้วิธีเข้าหาเราตอนที่เรากำลังปิดตัวยังไง?', 'How would you like your partner to reach you when you\'re closing off?'],
  ['ความสัมพันธ์นี้ทำให้เรากล้าฝันในเรื่องไหนมากขึ้น?', 'What has this relationship made you dare to dream about?'],
  ['มีความคิดไหนที่วนซ้ำในหัวตอนกลางคืนเกี่ยวกับเรา?', 'Is there a thought about us that keeps looping at night?'],
  ['อะไรคือสิ่งที่ยังไม่เคยขอโทษอย่างจริงจัง?', 'What have you never truly apologized for?'],
  ['ความไว้ใจที่เสียไปแล้ว สร้างใหม่ได้ไหมในความคิดของเรา?', 'Do you believe broken trust can be rebuilt?'],
  ['รู้สึกว่าความรักต้องแลกกับอะไรบ้าง?', 'What do you feel love has to cost?'],
  ['ถ้าความรู้สึกของเราตอนนี้เป็นสภาพอากาศ จะเป็นแบบไหน?', 'If your feelings about us right now were weather, what would they be?'],
  ['อะไรคือช่วงเวลาที่รู้สึกว่าอีกฝ่ายเลือกเราอีกครั้ง?', 'When did you feel your partner chose you all over again?'],
  ['มีความสงสัยในตัวเองที่ทำให้เราไม่กล้ารักเต็มที่ไหม?', 'Is there a self-doubt that stops you from loving fully?'],
  ['อยากให้อีกฝ่ายจดจำช่วงเวลาที่เราอ่อนแอที่สุดว่ายังไง?', 'How would you want your partner to remember you at your weakest?'],
  ['เคยรู้สึกว่าความรักทำให้เราเสียอิสรภาพไหม?', 'Have you ever felt love cost you your freedom?'],
  ['อะไรที่ทำให้เรารู้สึกเชื่อมต่อกับอีกฝ่ายแม้ในความเงียบ?', 'What makes you feel connected to your partner even in silence?'],
  ['ความรักครั้งนี้ทำให้เราเลิกเชื่อเรื่องไหนเกี่ยวกับตัวเอง?', 'What did this love make you stop believing about yourself?'],
  ['ถ้าอีกฝ่ายต้องการเวลาส่วนตัว เรามักตีความว่าอะไร?', 'When your partner needs time alone, how do you tend to read it?'],
  ['การถูกรักแบบไม่มีเงื่อนไขรู้สึกยังไงสำหรับเรา?', 'What does being loved unconditionally feel like to you?'],
  ['มีความโกรธต่อตัวเองที่ส่งผลต่อความสัมพันธ์บ้างไหม?', 'Is there anger at yourself that spills into our relationship?'],
  ['อะไรที่อยากได้รับการยอมรับจากอีกฝ่ายมากที่สุด?', 'What do you most want your partner to acknowledge about you?'],
  ['ความรักของเราเปลี่ยนนิยามคำว่า "บ้าน" ของเราไปยังไง?', 'How has our love changed what "home" means to you?'],
  ['มีบทสนทนาไหนที่ยังค้างคาและอยากกลับไปคุยให้จบ?', 'Is there an unfinished conversation you\'d like to return to?'],
  ['ถ้าเราเป็นพ่อแม่ในอนาคต อยากให้ลูกเห็นความรักของเราแบบไหน?', 'If we became parents someday, how would you want our children to see our love?'],
  ['อะไรที่ยากที่สุดในการเปิดใจให้คนหนึ่งคนรู้จักเราทั้งหมด?', 'What is the hardest part of letting one person know all of you?'],
  ['มีความต้องการไหนที่เรามักจะลดความสำคัญของมันเอง?', 'Which of your needs do you tend to downplay?'],
  ['เวลารู้สึกว่าไม่ได้รับความสำคัญ เราแสดงออกมายังไง?', 'How do you show it when you feel unimportant?'],
  ['ความรักช่วยให้เรารับมือกับความเหงาในชีวิตได้ดีขึ้นไหม?', 'Has love helped you cope better with life\'s loneliness?'],
  ['อะไรที่อยากปล่อยวางจากความสัมพันธ์เก่าให้ได้จริง ๆ?', 'What from past relationships do you truly want to let go of?'],
  ['อะไรทำให้รู้สึกว่า "พอแล้ว" ในความสัมพันธ์ทั่วไป?', 'In any relationship, what would make you feel "this is enough"?'],
  ['การเห็นอีกฝ่ายเจ็บปวดทำให้เรารู้สึกยังไงข้างใน?', 'How does seeing your partner in pain make you feel inside?'],
  ['มีความฝันร่วมกันที่กลัวว่าจะไม่เป็นจริงไหม?', 'Is there a shared dream you\'re afraid won\'t come true?'],
  ['อะไรที่ทำให้กล้าแสดงด้านที่ไม่สมบูรณ์ของเราให้อีกฝ่ายเห็น?', 'What makes you brave enough to show your partner your imperfect side?'],
  ['เวลาความต้องการของเราสองคนขัดกัน อยากให้เราตัดสินใจกันยังไง?', 'When our needs clash, how would you like us to decide?'],
  ['มีเรื่องไหนที่ยังรู้สึกอายที่จะยอมรับว่าต้องการ?', 'Is there something you still feel embarrassed to admit you need?'],
  ['ความสัมพันธ์นี้ทำให้เราเห็นความกลัวของตัวเองชัดขึ้นในเรื่องไหน?', 'Which of your fears has this relationship made clearer?'],
  ['อยากให้เราซ่อมแซมกันหลังทะเลาะยังไงให้รู้สึกว่าจบจริง?', 'How would you like us to repair after a fight so it feels truly resolved?'],
  ['อะไรคือสัญญาณว่าเรากำลังต้องการความช่วยเหลือแต่ไม่พูด?', 'What are the signs that you need help but aren\'t saying it?'],
  ['ความรักเปลี่ยนวิธีที่เรามองความสำเร็จยังไง?', 'How has love changed the way you see success?'],
  ['มีความรู้สึกแบบไหนที่กลัวว่าจะทำให้อีกฝ่ายรับไม่ไหว?', 'Is there a feeling you\'re afraid would be too much for your partner?'],
  ['อะไรที่อยากให้เราทั้งคู่เลิกทำกับความสัมพันธ์นี้?', 'What would you like us both to stop doing in this relationship?'],
  ['รู้สึกยังไงเวลาที่อีกฝ่ายเห็นเราร้องไห้?', 'How do you feel when your partner sees you cry?'],
  ['มีส่วนไหนในอดีตของอีกฝ่ายที่เราอยากเข้าใจมากขึ้น?', 'Which part of your partner\'s past would you like to understand better?'],
  ['อะไรทำให้รู้สึกว่าความรักไม่ได้แปลว่าต้องเห็นตรงกันทุกเรื่อง?', 'What taught you that love doesn\'t mean agreeing on everything?'],
  ['เคยรู้สึกว่าความสัมพันธ์นี้ช่วยชีวิตเราในช่วงไหนไหม?', 'Was there a time this relationship felt like it saved you?'],
  ['ความกลัวการเปลี่ยนแปลงส่งผลกับความรักของเรายังไง?', 'How does fear of change affect our love?'],
  ['อยากให้อีกฝ่ายเข้าใจจังหวะการเปิดใจของเรายังไง?', 'How would you like your partner to understand your pace of opening up?'],
  ['อะไรที่ทำให้เรากลับมาเลือกกันทุกวัน?', 'What makes us choose each other again every day?'],
  ['มีความทรงจำแย่ ๆ ที่อยากให้เราสร้างความทรงจำใหม่มาทับไหม?', 'Is there a bad memory you\'d like us to replace with a new one?'],
  ['ความรักทำให้เราเป็นคนที่ใจดีกับตัวเองมากขึ้นไหม?', 'Has love made you kinder to yourself?'],
  ['เวลาเราขัดแย้งกัน อะไรคือสิ่งที่กลัวจะเสียไปจริง ๆ?', 'When we clash, what are you really afraid of losing?'],
  ['มีคำว่า "รัก" แบบไหนที่อยากได้ยินแต่ยังไม่เคยได้ยิน?', 'Is there a way of saying "I love you" you\'ve longed to hear but never have?'],
  ['ถ้ามองความสัมพันธ์นี้จากอนาคต คิดว่าตัวเราในอนาคตจะขอบคุณเรื่องไหน?', 'Looking back from the future, what would your future self thank you for in this relationship?'],
  ['อะไรที่ทำให้รู้สึกว่าเราเติบโตเกินกว่าความกลัวเก่า ๆ แล้ว?', 'What makes you feel you\'ve outgrown old fears?'],
  ['อยากให้อีกฝ่ายรู้อะไรเกี่ยวกับวิธีที่เรารัก ที่อาจดูไม่ออกจากภายนอก?', 'What do you want your partner to know about how you love that might not show on the outside?'],
  ['ความสัมพันธ์ที่สุขภาพดีในแบบของเราหน้าตาเป็นยังไง?', 'What does a healthy relationship look like, in our own way?'],
  ['มีความต้องการไหนของอีกฝ่ายที่เราเพิ่งเข้าใจ?', 'Which of your partner\'s needs have you only recently understood?'],
  ['อะไรคือสิ่งที่อยากให้เราไม่เคยลืม แม้วันที่ยากที่สุด?', 'What do you want us never to forget, even on the hardest days?'],
  ['ถ้าเราสองคนพูดความจริงทั้งหมดได้คืนนี้โดยไม่มีใครเจ็บ อยากพูดเรื่องอะไรก่อน?', 'If we could speak every truth tonight without anyone getting hurt, what would you say first?'],
  ['ความรักครั้งนี้ทำให้เราเชื่อในอะไรมากขึ้น?', 'What has this love made you believe in more?'],
  ['อะไรคือส่วนที่ยังต้องเรียนรู้ในการรักอีกฝ่ายให้ดีขึ้น?', 'What do you still need to learn to love your partner better?'],
]
