// ครอบครัว — [ไทย, English]
// open: เปิดบทสนทนาแบบสบาย ๆ  ·  mid: ชวนนึกถึงความทรงจำและคุณค่า  ·  deep: เชิงลึก/จิตวิทยา
export const open = [
  ['อาหารจานไหนที่ทำให้คิดถึงบ้านเสมอ?', 'Which dish always makes you think of home?'],
  ['ถ้าครอบครัวได้ไปเที่ยวด้วยกันอีกครั้ง อยากไปที่ไหน?', 'If our family could take a trip together again, where would you go?'],
  ['เพลงไหนที่ได้ยินแล้วนึกถึงบ้าน?', 'Which song makes you think of home?'],
  ['ใครในบ้านทำอาหารอร่อยที่สุด และเมนูเด็ดคืออะไร?', 'Who is the best cook at home, and what is their signature dish?'],
  ['ถ้าครอบครัวเราเป็นหนัง จะเป็นหนังแนวไหน?', 'If our family were a movie, what genre would it be?'],
  ['วันหยุดแบบไหนที่อยากใช้กับครอบครัวมากที่สุด?', 'What kind of holiday would you most like to spend with family?'],
  ['ของเล่นชิ้นโปรดตอนเด็กคืออะไร?', 'What was your favorite toy as a child?'],
  ['ใครในบ้านที่ตลกที่สุดโดยไม่ตั้งใจ?', 'Who at home is the funniest without even trying?'],
  ['ขนมที่ต้องมีติดบ้านตลอดคืออะไร?', 'Which snack does our home always have?'],
  ['ถ้าครอบครัวเราเปิดร้านด้วยกัน จะเป็นร้านอะไร?', 'If our family opened a shop together, what would it be?'],
  ['มุมไหนในบ้านที่ชอบที่สุด?', 'Which corner of the house do you like best?'],
  ['รายการทีวีหรือหนังเรื่องไหนที่เคยดูด้วยกันทั้งบ้าน?', 'Which TV show or movie did the whole family watch together?'],
  ['ถ้าครอบครัวเราเป็นวงดนตรี ใครเล่นอะไร?', 'If our family were a band, who would play what?'],
  ['คำพูดติดปากของคนในบ้านที่ทุกคนจำได้คืออะไร?', 'What family catchphrase does everyone remember?'],
  ['เกมไหนที่เล่นด้วยกันแล้วสนุกที่สุด?', 'Which game is the most fun to play together?'],
  ['ใครในบ้านที่ตื่นเช้าที่สุด และใครตื่นสายที่สุด?', 'Who wakes up earliest at home, and who sleeps in the latest?'],
  ['ถ้าบ้านเรามีสัตว์เลี้ยงเพิ่มหนึ่งตัว อยากเลี้ยงอะไร?', 'If our home got one more pet, what would you want?'],
  ['เทศกาลไหนที่ชอบฉลองกับครอบครัวที่สุด?', 'Which festival do you love celebrating with family most?'],
  ['รูปครอบครัวรูปไหนที่ชอบที่สุด?', 'Which family photo is your favorite?'],
  ['ถ้าต้องตั้งชื่อทีมให้ครอบครัวเรา จะตั้งว่าอะไร?', 'If our family were a team, what would we be called?'],
  ['ของขวัญที่ได้จากคนในบ้านแล้วยังเก็บไว้คืออะไร?', 'Which gift from a family member are you still keeping?'],
  ['ใครในบ้านที่ถ่ายรูปเก่งที่สุด?', 'Who in the family takes the best photos?'],
  ['ร้านอาหารร้านไหนที่ครอบครัวไปบ่อยที่สุด?', 'Which restaurant does our family go to most often?'],
  ['ตอนเด็ก ๆ อยากเป็นอะไรเมื่อโตขึ้น?', 'What did you want to be when you grew up?'],
  ['ถ้าได้ใช้ชีวิตในบ้านหลังใหม่ อยากให้มีอะไรพิเศษ?', 'If we moved to a new house, what special feature would you want?'],
  ['ใครในบ้านที่ชอบร้องเพลงที่สุด?', 'Who at home loves singing the most?'],
  ['เมนูอาหารเช้าวันหยุดที่ชอบที่สุดคืออะไร?', 'What is your favorite weekend breakfast?'],
  ['ถ้าครอบครัวเราเป็นสัตว์หนึ่งชนิด จะเป็นตัวอะไร?', 'If our family were an animal, what would it be?'],
  ['กิจกรรมที่ทำด้วยกันแล้วทุกคนหัวเราะคืออะไร?', 'What activity together makes everyone laugh?'],
  ['ของใช้ชิ้นไหนในบ้านที่อยู่มานานที่สุด?', 'Which item in the house has been around the longest?'],
  ['ใครในบ้านที่เก่งเรื่องซ่อมของที่สุด?', 'Who at home is best at fixing things?'],
  ['ถ้าได้เลือกเมนูมื้อเย็นคืนนี้ จะเลือกอะไร?', 'If you could pick tonight\'s dinner, what would it be?'],
  ['ตอนเด็ก ๆ ชอบเล่นอะไรกับพี่น้องหรือญาติ?', 'What did you love playing with siblings or cousins as a kid?'],
  ['ทริปครอบครัวที่วุ่นวายที่สุดแต่จำได้ดีที่สุดคือทริปไหน?', 'Which family trip was the most chaotic but also the most memorable?'],
  ['ถ้าครอบครัวเรามีวันหยุดพิเศษของตัวเอง จะฉลองยังไง?', 'If our family had its own holiday, how would we celebrate?'],
  ['ใครในบ้านที่ชอบเล่าเรื่องเดิมซ้ำ ๆ?', 'Who at home loves retelling the same stories?'],
  ['สีไหนที่ทำให้นึกถึงบ้าน?', 'What color reminds you of home?'],
  ['ถ้าต้องอธิบายครอบครัวเราด้วยอีโมจิสามตัว จะเลือกอะไร?', 'If you described our family with three emojis, which would you choose?'],
  ['ขนมหรืออาหารที่ญาติผู้ใหญ่ทำให้แล้วไม่มีใครทำได้เหมือนคืออะไร?', 'What food did an elder make that no one else can recreate?'],
  ['ตอนเด็กเคยแอบทำอะไรแล้วโดนจับได้บ้าง?', 'What did you get caught sneakily doing as a kid?'],
  ['ใครในบ้านที่ทำให้ทุกคนตื่นเต้นกับวันเกิดเสมอ?', 'Who at home always makes birthdays exciting?'],
  ['ถ้าได้ทำงานอดิเรกใหม่ร่วมกันทั้งบ้าน อยากทำอะไร?', 'If the whole family took up a new hobby together, what would it be?'],
  ['ต้นไม้หรือมุมสวนไหนที่ผูกพันในบ้าน?', 'Which plant or garden spot at home do you feel attached to?'],
  ['ใครในบ้านที่มีลายมือสวยที่สุด?', 'Who in the family has the nicest handwriting?'],
  ['เมนูไหนที่อยากให้ครอบครัวสอนทำ?', 'Which dish would you like someone in the family to teach you?'],
  ['ช่วงเวลาไหนของวันที่บ้านอบอุ่นที่สุด?', 'What time of day does home feel warmest?'],
  ['ถ้าครอบครัวเราออกรายการเกมโชว์ จะชนะเพราะใคร?', 'If our family went on a game show, who would help us win?'],
  ['เคยมีชื่อเล่นตลก ๆ ที่คนในบ้านตั้งให้ไหม?', 'Did your family ever give you a funny nickname?'],
  ['ของฝากจากต่างจังหวัดที่ทุกคนในบ้านชอบคืออะไร?', 'Which treat from out of town does everyone at home love?'],
  ['ถ้าได้จัดงานรวมญาติ อยากให้มีกิจกรรมอะไร?', 'If you organized a family reunion, what activity would you include?'],
]

export const mid = [
  ['ความทรงจำในวัยเด็กที่อบอุ่นที่สุดคืออะไร?', 'What is your warmest childhood memory?'],
  ['มีเรื่องไหนที่อยากขอบคุณครอบครัวแต่ยังไม่เคยพูดออกมา?', 'Is there something you\'ve wanted to thank your family for but never said out loud?'],
  ['บทเรียนสำคัญที่สุดที่ได้เรียนรู้จากครอบครัวคืออะไร?', 'What is the most important lesson you learned from your family?'],
  ['อะไรคือประเพณีเล็ก ๆ ในบ้านที่รักที่สุด?', 'Which little family tradition at home do you love most?'],
  ['ถ้าให้เลือกหนึ่งวันในอดีตกลับมาใช้ร่วมกันอีกครั้ง จะเลือกวันไหน?', 'If you could live one day from the past together again, which would you choose?'],
  ['อะไรที่ทำให้รู้สึกว่า "บ้าน" คือบ้าน?', 'What makes "home" feel like home?'],
  ['ครั้งไหนที่รู้สึกภูมิใจในครอบครัวของเรามากที่สุด?', 'When have you been proudest of our family?'],
  ['มีคำสอนไหนของคนในครอบครัวที่ยังจำและใช้อยู่จนวันนี้?', 'Which piece of family wisdom do you still remember and live by today?'],
  ['อะไรคือสิ่งที่อยากส่งต่อให้คนรุ่นต่อไปในครอบครัว?', 'What would you like to pass on to the next generation of our family?'],
  ['ช่วงเวลายากลำบากไหนที่ครอบครัวผ่านมาด้วยกันได้?', 'What hard time has our family come through together?'],
  ['ถ้าให้บรรยายครอบครัวเราด้วยคำเดียว จะใช้คำว่าอะไร?', 'If you had to describe our family in one word, what would it be?'],
  ['ครั้งไหนที่ครอบครัวทำให้หัวเราะจนน้ำตาไหล?', 'When did your family make you laugh until you cried?'],
  ['มีเรื่องอะไรในอดีตของครอบครัวที่อยากรู้มากขึ้น?', 'What part of our family\'s past would you like to know more about?'],
  ['ถ้าเขียนจดหมายถึงครอบครัว อยากเริ่มต้นด้วยประโยคว่าอะไร?', 'If you wrote a letter to your family, how would you begin it?'],
  ['มีนิสัยหรือความชอบไหนที่ได้รับมาจากคนในครอบครัว?', 'Which habit or taste did you get from someone in your family?'],
  ['ช่วงเวลาไหนที่รู้สึกใกล้ชิดกับครอบครัวมากที่สุด?', 'When have you felt closest to your family?'],
  ['อะไรคือสิ่งที่อยากทำร่วมกันในครอบครัวให้บ่อยขึ้น?', 'What would you like our family to do together more often?'],
  ['เรื่องราวความรักของคนรุ่นก่อนในครอบครัวเป็นยังไง?', 'What are the love stories of the older generations in our family?'],
  ['อะไรที่ทำให้ภูมิใจในรากเหง้าของตัวเอง?', 'What makes you proud of where you come from?'],
  ['บทบาทในครอบครัวเปลี่ยนไปยังไงเมื่อโตขึ้น?', 'How has your role in the family changed as you have grown up?'],
  ['มีเรื่องเล่าประจำบ้านเรื่องไหนที่อยากได้ยินซ้ำอีกครั้ง?', 'Which family story would you love to hear told again?'],
  ['ถ้าให้ขอบคุณคนหนึ่งในครอบครัววันนี้ จะเป็นใครและเพราะอะไร?', 'If you could thank one person in the family today, who would it be and why?'],
  ['ความสุขในแบบครอบครัวเราหน้าตาเป็นยังไง?', 'What does happiness look like for our family?'],
  ['ตอนเด็ก ๆ ใครในบ้านที่เราวิ่งไปหาเป็นคนแรกเวลามีเรื่อง?', 'As a child, who at home did you run to first when something happened?'],
  ['ความทรงจำวันเกิดในวัยเด็กครั้งไหนที่ยังจำได้ชัด?', 'Which childhood birthday do you still remember clearly?'],
  ['ปู่ย่าตายายหรือญาติผู้ใหญ่คนไหนที่มีอิทธิพลกับเรามาก?', 'Which grandparent or elder has influenced you the most?'],
  ['อะไรที่พ่อแม่ทำแล้วเราเพิ่งเข้าใจตอนโต?', 'What did your parents do that you only understood as an adult?'],
  ['เคยรู้สึกว่าครอบครัวเป็นทีมเดียวกันจริง ๆ ตอนไหน?', 'When did you feel our family was truly a team?'],
  ['ถ้าครอบครัวเรามีคติประจำบ้าน จะเป็นประโยคว่าอะไร?', 'If our family had a motto, what would it be?'],
  ['มีของชิ้นไหนในบ้านที่มีเรื่องราวซ่อนอยู่?', 'Which object at home holds a hidden story?'],
  ['การย้ายบ้านหรือเปลี่ยนแปลงครั้งใหญ่ครั้งไหนที่ยังจำได้?', 'Which big move or change in the family do you still remember?'],
  ['พี่น้องหรือญาติคนไหนที่ทำให้เราเป็นคนแบบทุกวันนี้?', 'Which sibling or relative helped make you who you are today?'],
  ['ความสำเร็จของใครในบ้านที่อยากฉลองให้ใหญ่กว่านี้?', 'Whose achievement in the family deserved a bigger celebration?'],
  ['อยากให้ครอบครัวเรามีธรรมเนียมใหม่อะไรเพิ่ม?', 'What new tradition would you like our family to start?'],
  ['เวลาไหนที่รู้สึกว่าครอบครัวให้อภัยเรา?', 'When did you feel your family forgave you?'],
  ['ความทรงจำเรื่องอาหารในบ้านเรื่องไหนที่อบอุ่นที่สุด?', 'What is your warmest food memory from home?'],
  ['มีเพลงกล่อมหรือนิทานก่อนนอนที่ยังจำได้ไหม?', 'Do you still remember a lullaby or bedtime story?'],
  ['อะไรที่อยากถามพ่อแม่เกี่ยวกับตอนที่พวกท่านยังหนุ่มสาว?', 'What would you like to ask your parents about their younger years?'],
  ['ครั้งไหนที่ครอบครัวช่วยกันแก้ปัญหาได้ดีมาก?', 'When did our family solve a problem really well together?'],
  ['อยากให้วันอาทิตย์ของครอบครัวเราเป็นแบบไหน?', 'What would you like our family Sundays to look like?'],
  ['เรื่องอะไรที่ครอบครัวเราเห็นตรงกันเสมอ?', 'What does our family always agree on?'],
  ['ใครในบ้านที่เป็นคนรวมทุกคนไว้ด้วยกัน?', 'Who in the family keeps everyone together?'],
  ['มีความทรงจำเรื่องโรงเรียนที่ครอบครัวช่วยเราไว้ไหม?', 'Is there a school memory where your family came through for you?'],
  ['การเติบโตในบ้านนี้สอนอะไรเกี่ยวกับการแบ่งปัน?', 'What did growing up in this home teach you about sharing?'],
  ['อยากให้คนรุ่นต่อไปรู้เรื่องอะไรเกี่ยวกับครอบครัวเรา?', 'What do you want future generations to know about our family?'],
  ['ช่วงเทศกาลไหนที่บ้านคึกคักที่สุด และบรรยากาศเป็นยังไง?', 'Which holiday is the liveliest at home, and what is the atmosphere like?'],
  ['มีคำชมจากคนในบ้านที่ทำให้มั่นใจในตัวเองไหม?', 'Was there a compliment from family that made you feel confident?'],
  ['ใครในครอบครัวที่อยากใช้เวลาด้วยมากขึ้น?', 'Who in the family would you like to spend more time with?'],
  ['อะไรที่ครอบครัวทำแล้วทำให้รู้สึกปลอดภัย?', 'What does your family do that makes you feel safe?'],
  ['มีความทรงจำเรื่องการเดินทางไปบ้านญาติที่ประทับใจไหม?', 'Do you have a fond memory of visiting relatives?'],
  ['อาชีพของคนในครอบครัวส่งผลกับความฝันของเรายังไง?', 'How have your family members\' jobs shaped your dreams?'],
  ['มีบทสนทนาบนโต๊ะอาหารครั้งไหนที่จำได้ไม่ลืม?', 'Is there a dinner-table conversation you\'ve never forgotten?'],
  ['อยากให้ครอบครัวเรามีช่วงเวลาไม่ใช้โทรศัพท์ไหม และอยากทำอะไรแทน?', 'Would you like phone-free family time, and what would we do instead?'],
  ['ความแตกต่างระหว่างรุ่นในบ้านเราเรื่องไหนที่ตลกดี?', 'Which generation gap at home do you find funny?'],
  ['ความแตกต่างระหว่างรุ่นในบ้านเรื่องไหนที่อยากเข้าใจกันมากขึ้น?', 'Which generation gap at home would you like us to understand better?'],
  ['เคยเห็นพ่อแม่หรือผู้ปกครองกล้าหาญตอนไหน?', 'When have you seen a parent or guardian be brave?'],
  ['มีความทรงจำที่ทำให้รู้ว่าครอบครัวรักเรามากแค่ไหนไหม?', 'Is there a memory that showed you how much your family loves you?'],
  ['อยากให้ครอบครัวสนับสนุนความฝันของเรายังไง?', 'How would you like your family to support your dreams?'],
  ['ถ้าบ้านเรามีพิพิธภัณฑ์เล็ก ๆ จะจัดแสดงอะไรบ้าง?', 'If our home had a small museum, what would it display?'],
  ['ใครในครอบครัวที่สอนให้เรามีอารมณ์ขัน?', 'Who in the family taught you your sense of humor?'],
  ['การช่วยงานบ้านตอนเด็กสอนอะไรเราบ้าง?', 'What did helping with chores as a kid teach you?'],
  ['มีภาพในหัวของบ้านตอนเด็กที่ยังชัดอยู่ไหม?', 'Is there a picture of your childhood home that\'s still vivid in your mind?'],
  ['ความเชื่อหรือศาสนาในบ้านมีความหมายกับเรายังไง?', 'What do the beliefs or faith in our home mean to you?'],
  ['ช่วงที่ครอบครัวลำบาก ใครเป็นคนที่ทำให้ทุกคนมีกำลังใจ?', 'When the family was struggling, who kept everyone\'s spirits up?'],
  ['อยากให้วันเกิดของคนในบ้านฉลองกันแบบไหน?', 'How would you like us to celebrate birthdays at home?'],
  ['มีเรื่องไหนที่ครอบครัวเราทำได้ดีกว่าครอบครัวอื่น?', 'What does our family do better than most?'],
  ['ใครในบ้านที่เราเหมือนมากที่สุด และเหมือนตรงไหน?', 'Who in the family are you most like, and in what way?'],
  ['การเป็นพี่ คนกลาง หรือน้องคนเล็ก ส่งผลกับเรายังไง?', 'How has being the oldest, middle, or youngest shaped you?'],
  ['ถ้าได้จัดทริปพาพ่อแม่ไปเที่ยว อยากพาไปที่ไหน?', 'If you planned a trip for your parents, where would you take them?'],
  ['อยากเรียนรู้ทักษะอะไรจากคนรุ่นก่อนในบ้านก่อนจะสายเกินไป?', 'Which skill would you like to learn from the older generation before it\'s too late?'],
  ['ความทรงจำเรื่องการเจ็บป่วยที่ครอบครัวดูแลเราเป็นยังไง?', 'What do you remember about your family caring for you when you were sick?'],
  ['ช่วงไหนที่รู้สึกว่าเราเริ่มเป็นผู้ใหญ่ในสายตาครอบครัว?', 'When did you feel your family started seeing you as an adult?'],
  ['ครอบครัวเราแสดงความรักกันด้วยวิธีไหนมากที่สุด?', 'How does our family show love most often?'],
  ['มีเพื่อนบ้านหรือคนใกล้ชิดที่เหมือนเป็นครอบครัวไหม?', 'Is there a neighbor or close friend who feels like family?'],
  ['อยากให้บ้านในอนาคตของเรามีบรรยากาศแบบบ้านที่โตมาไหม?', 'Would you want your future home to feel like the home you grew up in?'],
  ['มีเรื่องที่ครอบครัวมักชวนคุยตอนกินข้าวไหม?', 'Is there a topic our family always talks about over meals?'],
  ['ใครในครอบครัวที่ให้คำแนะนำดีที่สุด?', 'Who in the family gives the best advice?'],
  ['เคยรู้สึกขอบคุณที่เกิดในครอบครัวนี้ตอนไหน?', 'When have you felt grateful to be born into this family?'],
  ['ความทรงจำเรื่องฝนตก น้ำท่วม หรือไฟดับที่บ้านเป็นยังไง?', 'Do you remember a rainstorm, flood, or blackout at home?'],
  ['ช่วงไหนที่รู้สึกว่าครอบครัวเปลี่ยนไปในทางที่ดี?', 'When did you feel our family changed for the better?'],
  ['มีของที่อยากเก็บไว้เป็นมรดกของครอบครัวไหม?', 'Is there something you\'d like to keep as a family heirloom?'],
  ['อยากให้ครอบครัวรู้จักเพื่อนหรือคนสำคัญของเรามากขึ้นไหม?', 'Would you like your family to know your friends or partner better?'],
  ['ใครในครอบครัวที่ทำให้เรารักการอ่านหรือการเรียนรู้?', 'Who in the family got you into reading or learning?'],
  ['อยากให้ครอบครัวเราดูแลสุขภาพด้วยกันแบบไหน?', 'How would you like our family to look after our health together?'],
  ['มีเรื่องอะไรที่อยากให้ครอบครัวเราหัวเราะเยาะตัวเองได้มากขึ้น?', 'What would you like our family to laugh at ourselves about more?'],
  ['ช่วงเวลาเงียบ ๆ กับคนในบ้านแบบไหนที่ชอบ?', 'What kind of quiet moments with family do you enjoy?'],
  ['ความทรงจำแรกสุดที่จำได้ในชีวิตเกี่ยวกับครอบครัวคืออะไร?', 'What is your very first memory of your family?'],
  ['ถ้าทำหนังสือรวมสูตรอาหารของบ้าน อยากให้มีเมนูอะไรบ้าง?', 'If we made a family recipe book, which dishes would you include?'],
  ['มีคำพูดของปู่ย่าตายายที่ยังจำได้ไหม?', 'Do you remember something a grandparent used to say?'],
  ['อะไรที่ทำให้ครอบครัวเราเป็นตัวของตัวเองไม่เหมือนใคร?', 'What makes our family uniquely us?'],
  ['ครั้งไหนที่ครอบครัวเซอร์ไพรส์เราได้มากที่สุด?', 'When did your family surprise you the most?'],
  ['อยากให้ครอบครัวเรารับมือกับความขัดแย้งแบบไหน?', 'How would you like our family to handle disagreements?'],
  ['มีช่วงไหนที่รู้สึกว่าได้ดูแลคนในบ้านกลับบ้าง?', 'When have you felt you were able to care for your family in return?'],
  ['อะไรที่ทำให้รู้สึกว่าครอบครัวยังเชื่อมกันอยู่แม้อยู่ห่างกัน?', 'What keeps our family connected even when we\'re apart?'],
  ['ความทรงจำไหนที่อยากสร้างกับครอบครัวก่อนสิ้นปีนี้?', 'What memory would you like to make with family before the end of this year?'],
  ['มีเกมหรือการละเล่นในวัยเด็กที่อยากสอนให้คนรุ่นต่อไปไหม?', 'Is there a childhood game you\'d like to teach the next generation?'],
  ['มีคำว่า "รัก" ที่อยากพูดกับใครในครอบครัววันนี้ไหม?', 'Is there someone in the family you want to say "I love you" to today?'],
  ['อะไรคือความหวังที่มีต่ออนาคตของครอบครัวเรา?', 'What do you hope for in our family\'s future?'],
  ['อะไรที่ชื่นชมในตัวคนในครอบครัวแต่ไม่ค่อยได้บอก?', 'What do you admire about someone in the family but rarely say?'],
  ['ความหมายของคำว่า "ครอบครัว" สำหรับเราคืออะไร?', 'What does the word "family" mean to you?'],
]

export const deep = [
  ['มีเรื่องอะไรของตัวเองที่ยังไม่เคยเล่าให้ครอบครัวฟัง?', 'Is there something about yourself you\'ve never told your family?'],
  ['เรื่องไหนที่อยากขอโทษคนในครอบครัวแต่ยังไม่มีโอกาส?', 'Is there something you want to apologize to a family member for but haven\'t had the chance?'],
  ['อะไรที่ทำให้รู้สึกถูกรักในครอบครัวนี้?', 'What makes you feel loved in this family?'],
  ['มีความฝันข้อไหนที่อยากให้ครอบครัวรับรู้และเข้าใจ?', 'Which of your dreams would you like your family to know about and understand?'],
  ['อะไรคือสิ่งที่อยากเข้าใจเกี่ยวกับพ่อแม่หรือคนในครอบครัวมากขึ้น?', 'What would you like to understand better about your parents or family?'],
  ['มีความกังวลอะไรที่อยากแบ่งปันกับครอบครัวไหม?', 'Is there a worry you would like to share with your family?'],
  ['อะไรที่เรียนรู้เรื่องความอดทนหรือการให้อภัยจากครอบครัว?', 'What has your family taught you about patience or forgiveness?'],
  ['มีความคาดหวังจากครอบครัวเรื่องไหนที่กดดันเรามากที่สุด?', 'Which of your family\'s expectations puts the most pressure on you?'],
  ['อะไรที่อยากให้พ่อแม่รู้แต่ไม่กล้าพูด?', 'What do you want your parents to know but haven\'t dared to say?'],
  ['ตอนเด็กมีช่วงไหนที่รู้สึกว่าไม่มีใครเข้าใจในบ้าน?', 'As a child, was there a time you felt no one at home understood you?'],
  ['การทะเลาะในบ้านครั้งไหนที่ยังติดอยู่ในใจ?', 'Which family argument still stays with you?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเป็นลูกที่ดีตลอดเวลา?', 'What makes you feel you always have to be the good child?'],
  ['มีบาดแผลในวัยเด็กที่อยากให้ครอบครัวรู้ไหม?', 'Is there a childhood hurt you\'d like your family to know about?'],
  ['รู้สึกยังไงเวลาถูกเปรียบเทียบกับพี่น้องหรือลูกบ้านอื่น?', 'How do you feel when you\'re compared to siblings or other people\'s children?'],
  ['ความรักในบ้านเราแสดงออกด้วยคำพูดน้อยไปไหม และรู้สึกยังไงกับมัน?', 'Does our family say "I love you" too rarely, and how do you feel about that?'],
  ['มีเรื่องที่พ่อแม่ทำแล้วเราสัญญากับตัวเองว่าจะไม่ทำแบบนั้น?', 'Is there something your parents did that you promised yourself you\'d never do?'],
  ['มีเรื่องที่พ่อแม่ทำแล้วเราอยากทำตามให้ได้?', 'Is there something your parents did that you hope to do too?'],
  ['ความกลัวที่ใหญ่ที่สุดเกี่ยวกับครอบครัวในอนาคตคืออะไร?', 'What is your biggest fear about our family\'s future?'],
  ['อะไรที่ทำให้ยากจะเปิดใจกับคนในบ้าน?', 'What makes it hard to open up to family?'],
  ['ช่วงไหนที่รู้สึกเหงาแม้อยู่ในบ้านที่มีคนเต็มไปหมด?', 'Have you ever felt lonely in a house full of people?'],
  ['มีความผิดหวังเล็ก ๆ ต่อครอบครัวที่เก็บไว้นานไหม?', 'Is there a small disappointment with your family you\'ve held for a long time?'],
  ['เรารู้สึกว่าต้องรับผิดชอบความสุขของคนในบ้านไหม?', 'Do you feel responsible for your family\'s happiness?'],
  ['อะไรคือสิ่งที่ไม่เคยได้ยินจากพ่อแม่แต่อยากได้ยิน?', 'What have you never heard from your parents but wish you had?'],
  ['ความสัมพันธ์กับพ่อหรือแม่เปลี่ยนไปยังไงเมื่อโตขึ้น?', 'How has your relationship with your father or mother changed as you\'ve grown?'],
  ['มีช่วงไหนที่รู้สึกว่าต้องโตเร็วเกินไปเพราะเรื่องในบ้าน?', 'Was there a time family circumstances made you grow up too fast?'],
  ['อะไรที่ทำให้กลัวทำให้ครอบครัวผิดหวัง?', 'What makes you afraid of disappointing your family?'],
  ['ความสำเร็จแบบที่ครอบครัวต้องการกับแบบที่เราต้องการ ต่างกันไหม?', 'Is the success your family wants for you different from what you want?'],
  ['เคยรู้สึกว่าเป็นคนนอกในครอบครัวตัวเองไหม?', 'Have you ever felt like an outsider in your own family?'],
  ['มีความลับในครอบครัวที่ส่งผลกับเราไหม?', 'Is there a family secret that has affected you?'],
  ['เวลาครอบครัวขัดแย้งกัน เรามักทำหน้าที่อะไร เป็นคนไกล่เกลี่ย หนี หรือเงียบ?', 'When the family clashes, what role do you play: peacemaker, escapee, or the quiet one?'],
  ['อะไรที่ทำให้ให้อภัยคนในครอบครัวได้ยาก?', 'What makes it hard to forgive a family member?'],
  ['การได้เห็นพ่อแม่แก่ตัวลงทำให้เรารู้สึกยังไง?', 'How does watching your parents grow older make you feel?'],
  ['มีคำถามไหนที่อยากถามพ่อแม่ก่อนจะไม่มีโอกาสได้ถาม?', 'Is there a question you want to ask your parents while you still can?'],
  ['ความเชื่อที่ได้จากบ้านข้อไหนที่กำลังตั้งคำถามอยู่?', 'Which belief from home are you now questioning?'],
  ['รู้สึกปลอดภัยพอที่จะร้องไห้ต่อหน้าครอบครัวไหม?', 'Do you feel safe enough to cry in front of your family?'],
  ['อะไรที่ครอบครัวไม่เคยพูดถึงแต่ทุกคนรู้?', 'What does our family never talk about even though everyone knows?'],
  ['ความกดดันเรื่องการเรียนหรืองานจากครอบครัวส่งผลกับเรายังไง?', 'How has family pressure about school or work affected you?'],
  ['มีช่วงไหนที่อยากให้ครอบครัวกอดเรามากกว่าสั่งสอน?', 'Was there a time you wished your family hugged you instead of lecturing you?'],
  ['การสูญเสียคนในครอบครัวเปลี่ยนเราไปยังไง?', 'How has losing a family member changed you?'],
  ['มีเรื่องที่รู้สึกผิดต่อพ่อแม่จนถึงวันนี้ไหม?', 'Is there something you still feel guilty about toward your parents?'],
  ['เราเรียนรู้วิธีจัดการความโกรธมาจากใครในบ้าน?', 'Who at home did you learn how to handle anger from?'],
  ['อะไรคือรูปแบบซ้ำ ๆ ในครอบครัวที่อยากหยุดไว้ที่รุ่นเรา?', 'Which family pattern would you like to end with your generation?'],
  ['เคยรู้สึกว่าความรักของพ่อแม่มีเงื่อนไขไหม?', 'Have you ever felt your parents\' love came with conditions?'],
  ['อะไรที่ทำให้รู้สึกว่าครอบครัวยอมรับเราอย่างที่เป็น?', 'What makes you feel your family accepts you as you are?'],
  ['มีส่วนไหนของตัวเองที่กลัวว่าครอบครัวจะรับไม่ได้?', 'Is there a part of you you fear your family couldn\'t accept?'],
  ['ช่วงไหนที่ครอบครัวทำให้เราเจ็บโดยไม่ตั้งใจ?', 'When has your family hurt you without meaning to?'],
  ['อยากให้ครอบครัวรู้อะไรเกี่ยวกับสุขภาพใจของเรา?', 'What would you like your family to know about your mental health?'],
  ['ความสัมพันธ์กับพี่น้องตอนนี้เป็นยังไง และอยากให้เป็นแบบไหน?', 'What is your relationship with your siblings like now, and how would you like it to be?'],
  ['การเป็นลูกคนโต คนกลาง หรือคนเล็ก ทำให้แบกอะไรไว้บ้าง?', 'What burdens come with being the oldest, middle, or youngest child?'],
  ['เวลาครอบครัวมีปัญหาเงิน เรารู้สึกและรับมือยังไง?', 'When the family has money troubles, how do you feel and cope?'],
  ['มีความโกรธต่อคนในบ้านที่ยังไม่ได้ปล่อยวางไหม?', 'Is there anger toward a family member you haven\'t let go of?'],
  ['อะไรที่อยากให้พ่อแม่ภูมิใจในตัวเรา นอกจากความสำเร็จ?', 'Besides achievements, what would you like your parents to be proud of you for?'],
  ['การเห็นพ่อแม่ทะเลาะกันตอนเด็กส่งผลกับความสัมพันธ์ของเราตอนนี้ไหม?', 'Did seeing your parents argue as a child affect your relationships now?'],
  ['ครอบครัวสอนให้เราซ่อนความรู้สึกแบบไหนไว้?', 'Which feelings did your family teach you to hide?'],
  ['อะไรคือสิ่งที่ยังเสียใจว่าไม่ได้ทำเพื่อครอบครัว?', 'What do you regret not doing for your family?'],
  ['เคยรู้สึกว่าต้องเลือกระหว่างความฝันของตัวเองกับความต้องการของครอบครัวไหม?', 'Have you ever had to choose between your dreams and your family\'s wishes?'],
  ['ความเงียบในบ้านทำให้รู้สึกสงบหรืออึดอัด?', 'Does silence at home feel peaceful or tense to you?'],
  ['อะไรที่ทำให้รู้สึกว่าเราไม่ได้รับความยุติธรรมในบ้าน?', 'What makes you feel treated unfairly at home?'],
  ['มีคนในครอบครัวที่อยากคืนดีด้วยไหม?', 'Is there a family member you\'d like to reconcile with?'],
  ['อะไรที่ทำให้กลับมาเชื่อใจคนในครอบครัวอีกครั้งหลังผิดหวัง?', 'What helps you trust a family member again after being let down?'],
  ['การเป็นพ่อแม่ที่ดีในความคิดของเราหน้าตาเป็นยังไง?', 'What does being a good parent look like to you?'],
  ['ถ้าได้คุยกับพ่อแม่ตอนอายุเท่าเรา อยากบอกอะไรพวกท่าน?', 'If you could talk to your parents when they were your age, what would you tell them?'],
  ['มีความทรงจำที่เจ็บแต่ทำให้ครอบครัวใกล้กันขึ้นไหม?', 'Is there a painful memory that brought the family closer?'],
  ['อะไรที่ทำให้รู้สึกว่าเราเป็นภาระของครอบครัว?', 'What makes you feel like a burden to your family?'],
  ['ความรักในครอบครัวสอนเราเรื่องความรักแบบอื่นยังไง?', 'How has family love shaped the way you love others?'],
  ['มีช่วงไหนที่อยากหนีออกจากบ้าน และตอนนั้นเกิดอะไรขึ้น?', 'Was there a time you wanted to run away from home, and what was happening?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเข้มแข็งให้คนในบ้านเห็น?', 'What makes you feel you have to look strong for your family?'],
  ['ความคาดหวังเรื่องการแต่งงานหรือการมีลูกจากครอบครัวทำให้รู้สึกยังไง?', 'How do your family\'s expectations about marriage or children make you feel?'],
  ['มีเรื่องที่ครอบครัวเข้าใจเราผิดมาตลอดไหม?', 'Is there something your family has always misunderstood about you?'],
  ['การได้รับการชื่นชมจากพ่อแม่สำคัญกับเราแค่ไหน?', 'How much does your parents\' approval matter to you?'],
  ['มีช่วงไหนที่รู้สึกว่าต้องดูแลพ่อแม่แทนที่พ่อแม่จะดูแลเรา?', 'Was there a time you had to look after your parents instead of them looking after you?'],
  ['อะไรคือสิ่งที่อยากรักษาไว้ แม้ครอบครัวจะเปลี่ยนไปแค่ไหน?', 'What do you want to keep, however much the family changes?'],
  ['ความทรงจำเรื่องการถูกลงโทษตอนเด็กส่งผลกับเรายังไง?', 'How has a childhood memory of being punished affected you?'],
  ['มีความรู้สึกไหนที่ไม่เคยกล้าแสดงต่อหน้าพ่อแม่?', 'Is there a feeling you\'ve never dared to show your parents?'],
  ['อะไรทำให้เราคิดว่าครอบครัวภูมิใจหรือไม่ภูมิใจในตัวเรา?', 'What makes you think your family is or isn\'t proud of you?'],
  ['เวลาครอบครัวไม่เห็นด้วยกับการตัดสินใจของเรา รู้สึกยังไง?', 'How do you feel when your family disagrees with your decisions?'],
  ['มีขอบเขตไหนที่อยากให้ครอบครัวเคารพมากขึ้น?', 'Which boundary would you like your family to respect more?'],
  ['การตั้งขอบเขตกับครอบครัวยากหรือง่ายสำหรับเรา?', 'Is setting boundaries with family hard or easy for you?'],
  ['อะไรที่อยากให้ครอบครัวถามเรามากกว่านี้?', 'What do you wish your family asked you about more?'],
  ['การเห็นคนในครอบครัวป่วยหนักเปลี่ยนมุมมองชีวิตเรายังไง?', 'How did seeing a family member seriously ill change your view of life?'],
  ['มีความเชื่อเรื่องตัวเองที่ได้มาจากคำพูดของคนในบ้านไหม?', 'Is there a belief about yourself that came from something said at home?'],
  ['อะไรคือแผลใจที่ครอบครัวช่วยเยียวยา?', 'What hurt has your family helped heal?'],
  ['อะไรคือแผลใจที่มาจากครอบครัวและยังเยียวยาอยู่?', 'What hurt came from your family that you\'re still healing?'],
  ['มีช่วงไหนที่พ่อแม่ขอโทษเรา และรู้สึกยังไง?', 'Has a parent ever apologized to you, and how did it feel?'],
  ['ถ้าพ่อแม่ไม่เคยขอโทษ อยากได้ยินคำขอโทษเรื่องอะไร?', 'If your parents never apologized, what would you want them to apologize for?'],
  ['ความรักของพ่อหรือแม่แบบไหนที่เราเพิ่งมองเห็น?', 'What kind of love from your father or mother have you only recently noticed?'],
  ['อะไรที่ทำให้กลัวจะเป็นเหมือนพ่อหรือแม่?', 'What makes you afraid of becoming like your father or mother?'],
  ['มีส่วนไหนที่ภูมิใจว่าได้เหมือนพ่อหรือแม่?', 'Which part of you are you proud to share with your father or mother?'],
  ['การย้ายออกจากบ้านหรือการจากบ้านไปไกลรู้สึกยังไง?', 'How did it feel to move out or live far from home?'],
  ['ช่วงไหนที่รู้สึกว่าบ้านไม่ใช่ที่ปลอดภัย และอะไรช่วยให้ผ่านมาได้?', 'Was there a time home didn\'t feel safe, and what helped you through?'],
  ['อะไรคือสิ่งที่อยากให้ครอบครัวหยุดพูดหรือหยุดทำ?', 'What would you like your family to stop saying or doing?'],
  ['ความแตกต่างทางความคิดกับครอบครัวเรื่องไหนที่ทำให้เหนื่อยใจ?', 'Which difference of opinion with your family wears you out?'],
  ['มีวิธีไหนที่ครอบครัวรักเราแต่เราไม่เคยสังเกต?', 'Is there a way your family loves you that you never noticed?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องพิสูจน์ตัวเองกับครอบครัว?', 'What makes you feel you have to prove yourself to your family?'],
  ['มีความทรงจำที่อยากลบออกจากวัยเด็กไหม?', 'Is there a childhood memory you wish you could erase?'],
  ['เวลารู้สึกแย่ เรามักเข้าหาครอบครัวหรือหลีกเลี่ยง?', 'When you feel low, do you turn to your family or avoid them?'],
  ['ความหวังที่ครอบครัวมีต่อเรา หนักหรือเบาแค่ไหน?', 'How heavy or light do your family\'s hopes for you feel?'],
  ['อะไรที่ทำให้เราเข้าใจว่าพ่อแม่ก็เป็นมนุษย์ธรรมดาคนหนึ่ง?', 'What made you realize your parents are ordinary humans too?'],
  ['มีเรื่องที่ยังไม่พร้อมเล่าให้ครอบครัวฟัง แต่อยากให้รู้ว่ามีอยู่ไหม?', 'Is there something you\'re not ready to tell your family but want them to know exists?'],
  ['การได้รับความช่วยเหลือจากครอบครัวทำให้รู้สึกอบอุ่นหรือรู้สึกติดหนี้?', 'Does help from family make you feel cared for or in debt?'],
  ['มีช่วงไหนที่อยากให้ครอบครัวฟังโดยไม่ต้องให้คำแนะนำ?', 'Was there a time you just wanted your family to listen without advising?'],
  ['ความเงียบหลังการทะเลาะในบ้านจบลงยังไงทุกครั้ง?', 'How does the silence after a family argument usually end?'],
  ['อยากให้ครอบครัวซ่อมแซมกันหลังทะเลาะยังไง?', 'How would you like our family to make up after a fight?'],
  ['อะไรคือสิ่งที่อยากได้รับการยอมรับจากครอบครัวมากที่สุด?', 'What do you most want your family to acknowledge about you?'],
  ['มีช่วงไหนที่รู้สึกว่าครอบครัวไม่เห็นความพยายามของเรา?', 'When did you feel your family didn\'t see your efforts?'],
  ['ความสัมพันธ์กับญาติผู้ใหญ่ที่จากไปแล้ว ยังมีอะไรค้างคาไหม?', 'Is anything unfinished with an elder who has passed away?'],
  ['ถ้าได้พูดกับคนในครอบครัวที่จากไปอีกครั้ง อยากพูดว่าอะไร?', 'If you could speak once more to a family member who has passed, what would you say?'],
  ['อะไรที่ทำให้รู้สึกว่ายังเป็นเด็กในสายตาครอบครัว?', 'What makes you feel you\'re still a child in your family\'s eyes?'],
  ['ความกลัวการสูญเสียพ่อแม่ส่งผลกับเรายังไง?', 'How does the fear of losing your parents affect you?'],
  ['มีเรื่องที่อยากให้พี่น้องรู้ว่าเราเคยปกป้องเขาไหม?', 'Is there a time you protected a sibling that you\'d like them to know about?'],
  ['การแข่งกันระหว่างพี่น้องส่งผลกับเราจนถึงวันนี้ไหม?', 'Does sibling rivalry still affect you today?'],
  ['อะไรที่ทำให้รู้สึกว่าครอบครัวรักคนอื่นมากกว่าเรา?', 'What has made you feel your family loved someone else more?'],
  ['อะไรที่ทำให้รู้สึกว่าเป็นคนสำคัญในครอบครัว?', 'What makes you feel important in the family?'],
  ['ความรู้สึกผิดที่อยู่ไกลบ้านมีบ้างไหม?', 'Do you ever feel guilty for being far from home?'],
  ['มีคำสัญญาที่ให้ไว้กับครอบครัวแล้วยังไม่ได้ทำไหม?', 'Is there a promise to your family you haven\'t kept yet?'],
  ['อะไรที่อยากขอบคุณตัวเองที่ผ่านเรื่องในบ้านมาได้?', 'What would you thank yourself for getting through at home?'],
  ['ความเชื่อเรื่องเพศหรือบทบาทในบ้านส่งผลกับเรายังไง?', 'How have beliefs about gender or roles at home affected you?'],
  ['ช่วงไหนที่รู้สึกว่าครอบครัวเลือกเรา?', 'When did you feel your family chose you?'],
  ['อะไรที่ทำให้ยอมรับคำวิจารณ์จากครอบครัวได้ยากกว่าจากคนอื่น?', 'Why is criticism from family harder to accept than from others?'],
  ['มีสิ่งที่อยากให้ครอบครัวรู้เกี่ยวกับความรักของเราไหม?', 'Is there something about your love life you\'d like your family to know?'],
  ['อยากให้ลูกหลานในอนาคตจำครอบครัวเราว่ายังไง?', 'How would you like future generations to remember our family?'],
  ['ความทรงจำเรื่องการถูกปลอบใจในวัยเด็กที่ยังอบอุ่นคืออะไร?', 'What childhood memory of being comforted still feels warm?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเก็บปัญหาไว้ไม่ให้ครอบครัวกังวล?', 'What makes you hide problems so your family won\'t worry?'],
  ['การเห็นพ่อแม่ร้องไห้ครั้งแรกเป็นยังไง?', 'What was it like the first time you saw a parent cry?'],
  ['มีความต้องการไหนที่ไม่เคยได้รับในบ้านแล้วพยายามหาจากที่อื่น?', 'Is there a need you didn\'t get at home that you\'ve looked for elsewhere?'],
  ['อะไรที่ครอบครัวทำให้รู้สึกว่าเรามีค่า?', 'What does your family do that makes you feel valued?'],
  ['การเติบโตในบ้านนี้ทำให้เรากลัวอะไรมากขึ้น?', 'What has growing up in this home made you more afraid of?'],
  ['การเติบโตในบ้านนี้ทำให้เรากล้าอะไรมากขึ้น?', 'What has growing up in this home made you braver about?'],
  ['มีความลับที่เก็บไว้เพื่อปกป้องคนในครอบครัวไหม?', 'Is there a secret you\'ve kept to protect someone in the family?'],
  ['เวลาไหนที่รู้สึกว่าครอบครัวต้องการเรามากที่สุด?', 'When have you felt your family needed you most?'],
  ['มีช่วงไหนที่รู้สึกว่าเราไม่ได้เป็นตัวเองเวลาอยู่บ้าน?', 'Are there times you don\'t feel like yourself at home?'],
  ['อะไรที่อยากให้พ่อแม่ใจดีกับตัวเองมากขึ้น?', 'In what way would you like your parents to be kinder to themselves?'],
  ['ความรักของปู่ย่าตายายต่างจากความรักของพ่อแม่ยังไง?', 'How is your grandparents\' love different from your parents\' love?'],
  ['มีบทสนทนาในบ้านที่ยังค้างคาและอยากกลับไปคุยให้จบไหม?', 'Is there an unfinished family conversation you\'d like to return to?'],
  ['อะไรที่ทำให้กลัวว่าความสัมพันธ์ในครอบครัวจะห่างกันไป?', 'What makes you afraid the family will drift apart?'],
  ['ความภาคภูมิใจที่ครอบครัวมีต่อกันแสดงออกมาแบบไหน?', 'How does our family show pride in one another?'],
  ['ถ้าครอบครัวอ่านใจเราได้หนึ่งวัน กลัวพวกเขาจะเห็นอะไร?', 'If your family could read your mind for a day, what would you fear they\'d see?'],
  ['มีเรื่องที่อยากให้ครอบครัวรู้ว่า "ไม่ใช่ความผิดของคุณ"?', 'Is there something you want your family to know is "not your fault"?'],
  ['อะไรคือความกลัวในวัยเด็กที่ครอบครัวไม่เคยรู้?', 'What childhood fear did your family never know about?'],
  ['การได้รับคำชมจากครอบครัวทำให้รู้สึกดีหรือเขิน?', 'Do compliments from family make you feel good or awkward?'],
  ['มีช่วงไหนที่ต้องเลือกข้างในครอบครัว และรู้สึกยังไง?', 'Have you ever had to take sides in the family, and how did it feel?'],
  ['ความหมายของการกตัญญูสำหรับเราคืออะไร?', 'What does gratitude toward parents mean to you?'],
  ['การดูแลพ่อแม่ในอนาคตทำให้รู้สึกยังไง?', 'How do you feel about caring for your parents in the future?'],
  ['อะไรที่อยากให้ครอบครัวเลิกกังวลเกี่ยวกับเรา?', 'What would you like your family to stop worrying about?'],
  ['มีความสัมพันธ์ในครอบครัวที่อยากซ่อมแต่ไม่รู้จะเริ่มยังไง?', 'Is there a family relationship you\'d like to mend but don\'t know how to start?'],
  ['ความเชื่อใจในครอบครัวเคยพังแล้วสร้างใหม่ได้ไหม?', 'Has trust in the family ever broken and been rebuilt?'],
  ['อะไรที่ทำให้รู้สึกว่าครอบครัวเป็นที่พักใจ?', 'What makes family a place of rest for you?'],
  ['ช่วงไหนที่ครอบครัวทำให้เรารู้สึกไม่โดดเดี่ยว?', 'When did your family make you feel less alone?'],
  ['มีความคิดที่วนซ้ำในหัวเกี่ยวกับครอบครัวตอนกลางคืนไหม?', 'Is there a thought about family that keeps looping at night?'],
  ['ความรักที่ไม่ได้พูดออกมาในบ้านเรา อยู่ในรูปแบบไหน?', 'What form does unspoken love take in our family?'],
  ['ถ้าครอบครัวเป็นครู กำลังสอนบทเรียนอะไรเราอยู่?', 'If our family were a teacher, what lesson is it teaching you now?'],
  ['มีความสำเร็จไหนที่อยากให้ครอบครัวรู้ว่าทำเพื่อพวกเขา?', 'Is there an achievement you\'d like your family to know was for them?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเป็นคนสมบูรณ์แบบในบ้าน?', 'What makes you feel you have to be perfect at home?'],
  ['การเห็นครอบครัวอื่นทำให้เรามองครอบครัวตัวเองยังไง?', 'How does seeing other families change how you see your own?'],
  ['ช่วงไหนที่รู้สึกว่าเราดูแลคนในบ้านมากกว่าดูแลตัวเอง?', 'When have you cared for your family more than for yourself?'],
  ['อะไรคือความหวังที่ยังไม่กล้าบอกครอบครัว?', 'What hope haven\'t you dared to tell your family?'],
  ['มีคำที่อยากพูดกับพี่น้องแต่ยังไม่กล้าไหม?', 'Is there something you\'d like to say to a sibling but haven\'t dared?'],
  ['ความแตกต่างระหว่างที่บ้านกับที่โลกภายนอกมองเรา ทำให้รู้สึกยังไง?', 'How do you feel about the gap between how home sees you and how the world does?'],
  ['อะไรที่ทำให้เราเข้าใจความเหนื่อยของพ่อแม่มากขึ้น?', 'What helped you understand your parents\' exhaustion?'],
  ['มีความเสียสละของคนในบ้านที่ยังไม่เคยขอบคุณไหม?', 'Is there a sacrifice by someone at home you\'ve never thanked them for?'],
  ['การได้เป็นตัวของตัวเองในบ้าน ยากแค่ไหน?', 'How hard is it to be fully yourself at home?'],
  ['อะไรที่ทำให้กลัวว่าจะไม่มีบ้านให้กลับ?', 'What makes you afraid of having no home to return to?'],
  ['ความรักแบบไหนที่อยากมอบให้ครอบครัวของตัวเองในอนาคต?', 'What kind of love do you want to give your own future family?'],
  ['มีด้านไหนของพ่อแม่ที่อยากรู้จักมากขึ้นในฐานะคนหนึ่งคน?', 'What side of your parents would you like to know better as people?'],
  ['อะไรที่ทำให้รู้สึกว่าครอบครัวมองข้ามความรู้สึกของเรา?', 'What makes you feel your family overlooks your feelings?'],
  ['เคยรู้สึกว่าต้องเป็นคนกลางระหว่างพ่อกับแม่ไหม?', 'Have you ever felt caught in the middle between your parents?'],
  ['การหย่าร้างหรือการแยกทางในครอบครัวส่งผลกับเรายังไง (ถ้ามี)?', 'If there was a divorce or separation in the family, how did it affect you?'],
  ['มีช่วงไหนที่อยากให้ครอบครัวภูมิใจในตัวเราเพียงเพราะเราเป็นเรา?', 'Have you wished your family were proud of you simply for being you?'],
  ['อะไรคือความสุขในบ้านที่กลัวจะเสียไปที่สุด?', 'What happiness at home are you most afraid of losing?'],
  ['ความอดทนของครอบครัวต่อเราในช่วงไหนที่ทำให้ซึ้งใจ?', 'When did your family\'s patience with you move you?'],
  ['อะไรที่ทำให้รู้สึกว่าเราไม่ได้รับการมองเห็นในบ้าน?', 'What makes you feel unseen at home?'],
  ['มีความรู้สึกที่ไม่มีคำเรียกแต่รู้สึกกับครอบครัวบ่อย ๆ ไหม?', 'Is there a feeling about your family you often have but have no word for?'],
  ['การให้อภัยพ่อแม่จำเป็นสำหรับการเติบโตของเราไหม?', 'Is forgiving your parents necessary for your own growth?'],
  ['ช่วงไหนที่รู้สึกว่าครอบครัวเปลี่ยนชีวิตเราไปตลอดกาล?', 'When did your family change your life forever?'],
  ['อะไรที่อยากปล่อยวางจากอดีตของครอบครัวให้ได้จริง ๆ?', 'What from the family\'s past do you truly want to let go of?'],
  ['มีความคาดหวังที่ไม่เคยพูดออกมาแต่หวังว่าครอบครัวจะเข้าใจไหม?', 'Is there an unspoken expectation you hope your family will understand?'],
  ['ถ้าพ่อแม่ได้อ่านจดหมายจากเราหนึ่งฉบับ อยากให้รู้อะไรมากที่สุด?', 'If your parents read one letter from you, what would you most want them to know?'],
  ['อะไรทำให้รู้สึกว่าครอบครัวเป็นทั้งความสุขและความท้าทายในเวลาเดียวกัน?', 'What makes family both a joy and a challenge at the same time?'],
  ['การได้ใช้เวลากับคนแก่ในบ้านสอนเรื่องเวลาและชีวิตยังไง?', 'What has time with the elders at home taught you about life and time?'],
  ['มีช่วงไหนที่เราต้องเป็นผู้ใหญ่ให้คนในบ้านทั้งที่ข้างในยังเปราะบาง?', 'When did you have to be the grown-up at home while feeling fragile inside?'],
  ['อะไรที่ทำให้รู้สึกว่าความรักในบ้านต้องแลกด้วยการเชื่อฟัง?', 'What makes you feel love at home has to be earned through obedience?'],
  ['มีช่วงไหนที่อยากให้ครอบครัวถามว่า "เป็นยังไงบ้าง" แล้วตั้งใจฟังคำตอบจริง ๆ?', 'When did you wish your family asked "how are you really?" and listened to the answer?'],
  ['ความกลัวที่จะทำให้คนในบ้านเสียใจทำให้เราไม่กล้าทำอะไรบ้าง?', 'What has the fear of upsetting your family stopped you from doing?'],
  ['มีส่วนไหนในตัวเราที่ครอบครัวรักแต่เรายังไม่รักตัวเอง?', 'Is there a part of you your family loves that you don\'t love yet?'],
  ['ความทรงจำเรื่องการถูกทิ้งให้อยู่คนเดียวตอนเด็กมีไหม และรู้สึกยังไง?', 'Do you remember being left alone as a child, and how did it feel?'],
  ['อะไรคือคำพูดของคนในบ้านที่ช่วยชีวิตเราในวันที่แย่?', 'What did someone at home say that saved you on a bad day?'],
  ['เวลาครอบครัวผิดหวังในตัวเรา เรารู้สึกยังไงข้างใน?', 'How do you feel inside when your family is disappointed in you?'],
  ['มีความต้องการไหนที่รู้สึกผิดที่จะขอจากครอบครัว?', 'Is there a need you feel guilty asking your family for?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเลือกระหว่างความสุขของตัวเองกับความสุขของคนในบ้าน?', 'What makes you feel you must choose between your happiness and your family\'s?'],
  ['การเห็นครอบครัวยอมรับความผิดพลาดของเราครั้งไหนที่ทำให้โล่งใจ?', 'When did your family accept a mistake of yours in a way that brought relief?'],
  ['มีคนในครอบครัวที่เราอยากเข้าใจแต่ยังเข้าไม่ถึงไหม?', 'Is there a family member you want to understand but can\'t quite reach?'],
  ['ถ้าเราเป็นพ่อแม่ของตัวเองตอนเด็ก อยากบอกเด็กคนนั้นว่าอะไร?', 'If you could parent your childhood self, what would you tell that child?'],
  ['อะไรคือสิ่งที่ยังต้องเรียนรู้ในการเป็นคนในครอบครัวที่ดีขึ้น?', 'What do you still need to learn to be a better family member?'],
  ['ครอบครัวช่วยให้เราเข้าใจคำว่า "รักโดยไม่มีเงื่อนไข" ไหม?', 'Has your family helped you understand "unconditional love"?'],
  ['อะไรที่ทำให้รู้สึกว่าความสัมพันธ์ในบ้านกำลังดีขึ้น?', 'What makes you feel things at home are getting better?'],
  ['มีความเจ็บปวดที่คนในบ้านแบกไว้แล้วเราอยากช่วยแบ่งไหม?', 'Is there pain someone at home carries that you\'d like to help share?'],
  ['อยากให้ครอบครัวรู้อะไรเกี่ยวกับวันที่เราเงียบไป?', 'What would you like your family to know about the days you go quiet?'],
  ['ความสัมพันธ์กับครอบครัวทำให้เรามองตัวเองยังไง?', 'How has your relationship with your family shaped how you see yourself?'],
  ['ถ้าคืนนี้ครอบครัวพูดความจริงได้ทุกเรื่องโดยไม่มีใครเจ็บ อยากพูดเรื่องอะไรก่อน?', 'If our family could speak every truth tonight without anyone getting hurt, what would you say first?'],
  ['ครอบครัวนี้ทำให้เราเชื่อในอะไรมากขึ้น?', 'What has this family made you believe in more?'],
]
