// เพื่อน ๆ — [ไทย, English]
// open: เปิดบทสนทนาแบบสบาย ๆ  ·  mid: ชวนนึกถึงความทรงจำและคุณค่า  ·  deep: เชิงลึก/จิตวิทยา
export const open = [
  ['ถ้าเราสองคนได้ไปเที่ยวด้วยกันพรุ่งนี้ อยากไปที่ไหน?', 'If we could go on a trip together tomorrow, where would you go?'],
  ['ร้านอาหารร้านไหนที่ต้องพาเพื่อนคนนี้ไปให้ได้?', 'Which restaurant do you absolutely have to take this friend to?'],
  ['เพลงไหนที่ฟังแล้วนึกถึงช่วงเวลาที่อยู่ด้วยกัน?', 'Which song reminds you of our time together?'],
  ['ถ้ามิตรภาพของเราเป็นหนัง จะเป็นหนังแนวไหน?', 'If our friendship were a movie, what genre would it be?'],
  ['มุกตลกประจำกลุ่มของเรามีอะไรบ้าง?', 'What are our running inside jokes?'],
  ['ถ้าได้เปิดธุรกิจกับเพื่อนคนนี้ จะขายอะไร?', 'If you started a business with this friend, what would you sell?'],
  ['ใครในกลุ่มมีแนวโน้มจะกลายเป็นคนดังมากที่สุด?', 'Who in our group is most likely to become famous?'],
  ['ของกินเล่นอะไรที่ต้องมีทุกครั้งที่เจอกัน?', 'Which snack is a must every time we hang out?'],
  ['ถ้าเราติดอยู่บนเกาะร้างด้วยกัน ใครจะรอดนานกว่า?', 'If we were stranded on a desert island, who would last longer?'],
  ['กิจกรรมไหนที่อยากลองทำกับเพื่อนสักครั้ง?', 'What activity would you like to try with this friend at least once?'],
  ['ฉายาที่เหมาะกับเพื่อนคนนี้ที่สุดคืออะไร?', 'What nickname suits this friend best?'],
  ['ถ้าต้องเลือกสัตว์แทนตัวเพื่อนคนนี้ จะเป็นตัวอะไร?', 'If this friend were an animal, which one would they be?'],
  ['ซีรีส์เรื่องไหนที่อยากชวนเพื่อนคนนี้ดูด้วยกัน?', 'Which series would you love to binge with this friend?'],
  ['วันหยุดแบบไหนที่อยากใช้กับเพื่อนมากที่สุด?', 'What kind of day off would you most like to spend with your friends?'],
  ['ใครในกลุ่มที่มักมาสายที่สุด และข้ออ้างที่ดีที่สุดคืออะไร?', 'Who in the group is always late, and what was their best excuse?'],
  ['ถ้าเราเป็นวงดนตรี ใครเล่นอะไร?', 'If we were a band, who would play what?'],
  ['อาหารจานไหนที่ทำแล้วอยากให้เพื่อนชิม?', 'Which dish would you love your friend to taste?'],
  ['ถ้าได้ทำคลิปด้วยกันหนึ่งคลิป จะเป็นคลิปแนวไหน?', 'If we made one video together, what kind would it be?'],
  ['ของฝากชิ้นไหนจากเพื่อนที่ยังเก็บไว้?', 'Which souvenir from a friend are you still keeping?'],
  ['ถ้าเพื่อนคนนี้เป็นตัวละครการ์ตูน จะเป็นใคร?', 'If this friend were a cartoon character, who would they be?'],
  ['คำพูดติดปากของเพื่อนคนนี้คืออะไร?', 'What is this friend\'s catchphrase?'],
  ['ใครในกลุ่มที่ถ่ายรูปเก่งที่สุด และใครถ่ายแย่ที่สุด?', 'Who in the group takes the best photos, and who takes the worst?'],
  ['ถ้ามีเงินก้อนให้ใช้ด้วยกันหนึ่งวัน อยากทำอะไร?', 'If we had a pile of money to spend together for one day, what would we do?'],
  ['เกมไหนที่เล่นด้วยกันแล้วทะเลาะกันทุกที?', 'Which game always ends in an argument when we play it?'],
  ['สถานที่ไหนที่เป็นจุดนัดเจอประจำของเรา?', 'Where is our usual meet-up spot?'],
  ['ถ้าต้องจัดปาร์ตี้วันเกิดเซอร์ไพรส์ให้เพื่อนคนนี้ จะมีธีมอะไร?', 'If you threw this friend a surprise birthday party, what would the theme be?'],
  ['เคยมีเรื่องอะไรที่ทำด้วยกันแล้วไม่กล้าเล่าให้พ่อแม่ฟัง?', 'Is there something we did together you\'d never tell your parents about?'],
  ['ถ้าเราสลับชีวิตกันหนึ่งวัน คิดว่าใครจะลำบากกว่า?', 'If we swapped lives for a day, who do you think would struggle more?'],
  ['ทักษะไหนของเพื่อนที่อยากขอยืมมาใช้บ้าง?', 'Which of your friend\'s skills would you like to borrow?'],
  ['รูปไหนของเราที่เห็นแล้วต้องขำทุกครั้ง?', 'Which photo of us makes you laugh every time?'],
  ['ถ้าต้องเลือกประเทศให้เพื่อนคนนี้ไปอยู่ จะเลือกที่ไหน?', 'If you picked a country for this friend to live in, where would it be?'],
  ['เรื่องไหนที่เรามักจะเถียงกันแบบไม่มีวันจบ?', 'What topic do we argue about endlessly?'],
  ['ใครในกลุ่มที่ทำอาหารอร่อยที่สุด?', 'Who in the group is the best cook?'],
  ['ถ้ามิตรภาพเรามีเพลงประจำ จะเป็นเพลงอะไร?', 'If our friendship had a theme song, what would it be?'],
  ['กิจกรรมที่ทำด้วยกันแล้วหัวเราะหนักที่สุดคืออะไร?', 'What activity together made us laugh the hardest?'],
  ['ถ้าได้ไปคอนเสิร์ตด้วยกัน อยากไปดูใคร?', 'If we went to a concert together, who would you want to see?'],
  ['ใครในกลุ่มที่มีแนวโน้มจะหลงทางมากที่สุด?', 'Who in the group is most likely to get lost?'],
  ['ถ้าเพื่อนคนนี้เปิดช่องยูทูบ จะเป็นช่องเกี่ยวกับอะไร?', 'If this friend started a YouTube channel, what would it be about?'],
  ['ของที่ยืมเพื่อนไปแล้วยังไม่ได้คืนมีอะไรบ้าง?', 'What have you borrowed from a friend and never returned?'],
  ['ถ้าเราจะสักลายคู่กัน จะเป็นลายอะไร?', 'If we got matching tattoos, what would they be?'],
  ['ทริปไหนที่อยากไปซ้ำอีกครั้ง?', 'Which trip would you love to do again?'],
  ['ใครในกลุ่มที่ส่งสติกเกอร์เยอะที่สุด?', 'Who in the group sends the most stickers?'],
  ['ถ้าต้องอธิบายเพื่อนคนนี้ด้วยอีโมจิสามตัว จะเลือกอะไร?', 'If you described this friend with three emojis, which would you choose?'],
  ['ของขวัญที่ดีที่สุดที่เคยได้จากเพื่อนคืออะไร?', 'What is the best gift a friend has ever given you?'],
  ['ถ้าได้ลองอาชีพของเพื่อนหนึ่งวัน อยากลองไหม?', 'Would you want to try your friend\'s job for a day?'],
  ['เราสองคนเหมือนกันในเรื่องไหนจนน่าตกใจ?', 'In what way are we surprisingly alike?'],
  ['ถ้าได้ไปแคมป์ปิ้งด้วยกัน ใครจะเป็นคนกางเต็นท์?', 'If we went camping, who would pitch the tent?'],
  ['ใครในกลุ่มที่ชอบเล่าเรื่องเดิมซ้ำ ๆ?', 'Who in the group loves retelling the same stories?'],
  ['ถ้ามีวันพิเศษของมิตรภาพเรา จะฉลองยังไง?', 'If our friendship had its own holiday, how would we celebrate it?'],
  ['ตอนนี้กำลังติดอะไรอยู่ และอยากชวนเพื่อนมาติดด้วยไหม?', 'What are you hooked on right now, and would you get your friend into it?'],
]

export const mid = [
  ['ความทรงจำที่ตลกที่สุดที่เรามีร่วมกันคืออะไร?', 'What is the funniest memory we share?'],
  ['อะไรที่ทำให้เรากลายมาเป็นเพื่อนสนิทกัน?', 'What made us become close friends?'],
  ['มีเรื่องไหนที่อยากขอบคุณเพื่อนคนนี้แต่ยังไม่เคยพูด?', 'Is there something you\'ve wanted to thank this friend for but never said?'],
  ['ช่วงชีวิตไหนที่รู้สึกดีใจที่สุดที่มีเพื่อนคนนี้อยู่ข้าง ๆ?', 'At what point in your life were you most glad to have this friend by your side?'],
  ['ถ้าให้บรรยายเพื่อนคนนี้ด้วยคำเดียว จะใช้คำว่าอะไร?', 'If you had to describe this friend in one word, what would it be?'],
  ['ครั้งไหนที่เพื่อนช่วยเราไว้โดยที่อาจไม่รู้ตัว?', 'When did your friend help you without maybe even realizing it?'],
  ['ถ้าย้อนเวลากลับไปได้ อยากกลับไปวันไหนที่อยู่ด้วยกัน?', 'If you could go back in time, which day together would you return to?'],
  ['มีนิสัยไหนที่เปลี่ยนไปเพราะเพื่อนคนนี้?', 'Which of your habits has changed because of this friend?'],
  ['ความสำเร็จเล็ก ๆ ล่าสุดที่ภูมิใจแต่ยังไม่ได้เล่าคืออะไร?', 'What\'s a recent small win you\'re proud of but haven\'t told anyone about?'],
  ['ถ้าต้องออกผจญภัยด้วยกันสักครั้ง อยากทำอะไร?', 'If we went on one adventure together, what would you want to do?'],
  ['อะไรที่ทำให้หัวเราะได้เสมอเมื่อคิดถึงกัน?', 'What always makes you laugh when you think of each other?'],
  ['ถ้าให้เขียนคำอวยพรให้เพื่อนคนนี้ อยากอวยพรว่าอะไร?', 'If you wrote this friend a wish, what would you wish for them?'],
  ['อะไรคือสิ่งที่ชื่นชมในตัวเพื่อนคนนี้มากที่สุด?', 'What do you admire most about this friend?'],
  ['ถ้าชีวิตเป็นหนัง ตอนนี้กำลังอยู่ในฉากแบบไหน?', 'If life were a movie, what kind of scene are you in right now?'],
  ['อะไรที่อยากลองทำแต่ยังไม่กล้า?', 'What would you like to try but haven\'t dared to yet?'],
  ['มีเรื่องอะไรในอดีตที่ยังคิดถึงอยู่บ่อย ๆ?', 'What from the past do you still think about often?'],
  ['อะไรคือสิ่งที่ทำให้ช่วงนี้ของชีวิตพิเศษ?', 'What makes this time of your life special?'],
  ['ถ้าเลือกได้ อยากให้มิตรภาพของเราเป็นแบบไหนในอีก 10 ปี?', 'If you could choose, what would you want our friendship to be like in ten years?'],
  ['เรื่องเล็ก ๆ อะไรที่ทำให้วันนี้ดีขึ้น?', 'What small thing made your day better today?'],
  ['มีสิ่งไหนที่เรียนรู้เกี่ยวกับตัวเองจากเพื่อนคนนี้?', 'What have you learned about yourself from this friend?'],
  ['ช่วงเวลาไหนที่รู้สึกภูมิใจในตัวเพื่อนคนนี้?', 'When have you felt proud of this friend?'],
  ['ถ้าต้องเลือกเก็บความทรงจำเดียวไว้ตลอดไป จะเลือกอันไหน?', 'If you could keep only one memory forever, which would you choose?'],
  ['อะไรคือคำแนะนำที่ดีที่สุดที่เคยได้รับจากเพื่อน?', 'What is the best advice a friend has ever given you?'],
  ['เรื่องอะไรที่อยากให้เราสองคนได้ทำด้วยกันเร็ว ๆ นี้?', 'What would you like the two of us to do together soon?'],
  ['ความประทับใจแรกที่มีต่อกันเป็นยังไง และตอนนี้เปลี่ยนไปไหม?', 'What was your first impression of each other, and has it changed?'],
  ['เพื่อนคนนี้เก่งเรื่องไหนที่ตัวเองอาจไม่รู้?', 'What is this friend great at without realizing it?'],
  ['ช่วงไหนที่มิตรภาพของเราแน่นแฟ้นขึ้นมาก?', 'When did our friendship grow much stronger?'],
  ['มีคำพูดไหนของเพื่อนที่ยังจำได้จนวันนี้?', 'Is there something your friend said that you still remember?'],
  ['เวลาเพื่อนคนนี้เศร้า เรามักทำอะไรให้?', 'What do you usually do when this friend is sad?'],
  ['ถ้าต้องพาเพื่อนคนนี้ไปรู้จักครอบครัว อยากให้ครอบครัวเห็นเพื่อนในมุมไหน?', 'If you introduced this friend to your family, what side of them would you want your family to see?'],
  ['อะไรที่ทำให้มิตรภาพนี้ต่างจากมิตรภาพอื่น?', 'What makes this friendship different from others?'],
  ['เป้าหมายส่วนตัวในปีนี้คืออะไร และอยากให้เพื่อนช่วยเรื่องไหน?', 'What is your personal goal this year, and how could your friend help?'],
  ['ช่วงที่ห่างกันไป อะไรที่ทำให้เรากลับมาคุยกันเหมือนเดิม?', 'When we drifted apart, what brought us back to talking like before?'],
  ['ความทรงจำสมัยเรียนเรื่องไหนที่ยังเล่าซ้ำได้ไม่เบื่อ?', 'Which school memory never gets old?'],
  ['ใครในกลุ่มที่เป็นที่พึ่งทางใจของทุกคน?', 'Who in our group is everyone\'s emotional anchor?'],
  ['เพื่อนคนนี้ทำให้เรากล้าทำอะไรที่ไม่เคยคิดว่าจะทำ?', 'What has this friend made you brave enough to do?'],
  ['ถ้าเพื่อนคนนี้ย้ายไปอยู่ไกล อะไรที่จะคิดถึงที่สุด?', 'If this friend moved far away, what would you miss most?'],
  ['มีความลับของกลุ่มที่เป็นความทรงจำดี ๆ ไหม?', 'Is there a group secret that\'s become a fond memory?'],
  ['เคยทะเลาะกันเรื่องอะไร แล้วคืนดีกันยังไง?', 'What did we once fight about, and how did we make up?'],
  ['อะไรที่ทำให้รู้สึกเป็นตัวเองได้เต็มที่เวลาอยู่กับเพื่อนคนนี้?', 'What lets you be completely yourself around this friend?'],
  ['ช่วงเวลาไหนที่เพื่อนทำให้รู้สึกไม่โดดเดี่ยว?', 'When did a friend make you feel less alone?'],
  ['มิตรภาพแบบไหนที่อยากมีให้ได้ตลอดชีวิต?', 'What kind of friendship do you want to keep for life?'],
  ['เพื่อนคนนี้สอนให้มองโลกต่างไปยังไง?', 'How has this friend taught you to see the world differently?'],
  ['ถ้าเราจะทำอะไรเพื่อสังคมด้วยกัน อยากทำอะไร?', 'If we did something for the community together, what would it be?'],
  ['อะไรที่อยากให้เพื่อนคนนี้รู้ว่าเราภูมิใจในตัวเขา?', 'What do you want this friend to know you\'re proud of them for?'],
  ['นิสัยไหนของเพื่อนที่ตอนแรกไม่ชอบ แต่ตอนนี้กลับชอบ?', 'Which of your friend\'s traits did you dislike at first but love now?'],
  ['เวลาไหนที่รู้สึกว่าเพื่อนคนนี้เข้าใจเราดีที่สุด?', 'When did you feel this friend understood you best?'],
  ['เราสองคนต่างกันตรงไหนที่ทำให้มิตรภาพนี้สนุก?', 'How are we different in ways that make this friendship fun?'],
  ['ถ้าต้องฝากเรื่องสำคัญหนึ่งเรื่องไว้กับเพื่อนคนนี้ จะฝากอะไร?', 'If you had to trust this friend with one important thing, what would it be?'],
  ['ความทรงจำการเดินทางด้วยกันครั้งไหนที่ประทับใจที่สุด?', 'Which trip together left the strongest impression on you?'],
  ['อะไรคือเรื่องที่อยากชวนเพื่อนคุยแต่ยังไม่มีโอกาส?', 'What have you wanted to talk about with your friend but haven\'t had the chance?'],
  ['มีความฝันวัยเด็กข้อไหนที่ยังอยากทำให้เป็นจริง?', 'Which childhood dream do you still want to make come true?'],
  ['เวลาเพื่อนมีความสุข เรารู้ได้ยังไง?', 'How can you tell when this friend is happy?'],
  ['การเป็นเพื่อนที่ดีสำหรับเราหมายถึงการทำอะไร?', 'To you, what does being a good friend involve?'],
  ['มีคำชมไหนจากเพื่อนที่ทำให้มั่นใจขึ้น?', 'Which compliment from a friend boosted your confidence?'],
  ['อยากให้เราเจอกันบ่อยแค่ไหน และทำอะไรด้วยกันเป็นประจำ?', 'How often would you like us to meet, and what would we do regularly?'],
  ['ใครในกลุ่มที่เปลี่ยนไปมากที่สุดตั้งแต่รู้จักกัน?', 'Who in our group has changed the most since we met?'],
  ['เคยเห็นเพื่อนคนนี้กล้าหาญตอนไหน?', 'When have you seen this friend be brave?'],
  ['ช่วงไหนในชีวิตที่อยากย้อนกลับไปเพราะมีเพื่อนอยู่ด้วย?', 'Which period of your life would you revisit because your friends were there?'],
  ['ความสัมพันธ์กับเพื่อนช่วยให้เราผ่านช่วงงานยุ่งหรือเรียนหนักยังไง?', 'How have friendships helped you through busy or stressful times?'],
  ['เพลงที่ร้องด้วยกันแล้วสนุกที่สุดคือเพลงอะไร?', 'Which song is the most fun to sing together?'],
  ['ถ้ามิตรภาพของเรามีกฎหนึ่งข้อ จะเป็นกฎว่าอะไร?', 'If our friendship had one rule, what would it be?'],
  ['อะไรที่เพื่อนคนนี้ทำแล้วทำให้รู้สึกได้รับความสำคัญ?', 'What does this friend do that makes you feel valued?'],
  ['มีเรื่องไหนที่เพื่อนเป็นคนแรกที่เรานึกถึงจะเล่าให้ฟัง?', 'What kind of news is this friend the first person you want to tell?'],
  ['เพื่อนแบบไหนที่อยากเป็นสำหรับคนอื่น?', 'What kind of friend do you want to be for others?'],
  ['อยากให้เราซัพพอร์ตความฝันของกันและกันยังไง?', 'How would you like us to support each other\'s dreams?'],
  ['ช่วงไหนที่รู้สึกว่าเราโตขึ้นไปด้วยกัน?', 'When have you felt us growing up together?'],
  ['มีงานหรือโปรเจกต์ไหนที่อยากทำร่วมกับเพื่อน?', 'Is there a project you\'d like to work on with your friend?'],
  ['ถ้าต้องให้คำแนะนำตัวเองตอนเพิ่งรู้จักกัน จะบอกว่าอะไร?', 'What advice would you give yourself back when we first met?'],
  ['ความทรงจำไหนที่อยากสร้างด้วยกันก่อนสิ้นปีนี้?', 'What memory would you like us to make before the end of this year?'],
  ['อะไรที่ทำให้กลับมาสนิทกันได้ทุกครั้งแม้ไม่ได้เจอกันนาน?', 'What lets us pick up right where we left off, even after a long time apart?'],
  ['เพื่อนคนนี้มีอิทธิพลกับรสนิยมของเราในเรื่องไหน?', 'How has this friend influenced your taste in things?'],
  ['ถ้าต้องบรรยายช่วงเวลาที่ดีที่สุดของเราให้คนอื่นฟัง จะเล่าว่าอะไร?', 'How would you describe our best moment together to someone else?'],
  ['การได้รับฟังแบบไหนที่ทำให้รู้สึกดีที่สุด?', 'What kind of listening makes you feel best?'],
  ['มีเรื่องที่อยากขอคำปรึกษาจากเพื่อนคนนี้ตอนนี้ไหม?', 'Is there something you\'d like this friend\'s advice on right now?'],
  ['อะไรที่ทำให้มิตรภาพนี้อยู่รอดผ่านการเปลี่ยนแปลงในชีวิต?', 'What has helped this friendship survive life\'s changes?'],
  ['ความสุขแบบไหนที่มีแค่ตอนอยู่กับเพื่อน?', 'What kind of happiness do you only feel with your friends?'],
  ['ชอบให้เพื่อนให้กำลังใจด้วยคำพูดหรือการกระทำ?', 'Do you prefer friends to encourage you with words or with actions?'],
  ['มีคนในชีวิตที่อยากให้เพื่อนคนนี้ได้รู้จักไหม?', 'Is there someone in your life you\'d like this friend to meet?'],
  ['อะไรที่ทำให้รู้สึกว่าเพื่อนคนนี้เป็นครอบครัวที่เราเลือกเอง?', 'What makes this friend feel like family you chose?'],
  ['ช่วงไหนที่ชีวิตยุ่งจนลืมดูแลมิตรภาพ และอยากแก้ไขยังไง?', 'When did life get so busy you neglected our friendship, and how would you make it up?'],
  ['เคยเห็นตัวเองผ่านสายตาเพื่อนในแบบที่ไม่คาดคิดไหม?', 'Have you ever seen yourself through a friend\'s eyes in a way that surprised you?'],
  ['ถ้าต้องเขียนจดหมายถึงเพื่อนคนนี้ในอีก 20 ปี จะเขียนว่าอะไร?', 'If you wrote this friend a letter to open in 20 years, what would it say?'],
  ['มีเรื่องอะไรที่อยากให้เรากล้าคุยกันตรง ๆ มากขึ้น?', 'What would you like us to be more direct with each other about?'],
  ['ใครในกลุ่มที่ทำให้บรรยากาศดีขึ้นเสมอ และทำยังไง?', 'Who in our group always lifts the mood, and how?'],
  ['ความสำเร็จของเพื่อนคนไหนที่ทำให้เราดีใจเหมือนเป็นของตัวเอง?', 'Whose success felt like your own?'],
  ['อะไรที่อยากเรียนรู้จากเพื่อนคนนี้?', 'What would you like to learn from this friend?'],
  ['ถ้ามิตรภาพเรามีหนังสือหนึ่งเล่ม บทที่สนุกที่สุดจะเป็นเรื่องอะไร?', 'If our friendship were a book, what would the best chapter be about?'],
  ['ช่วงไหนที่เพื่อนเป็นคนที่ทำให้เราไม่ยอมแพ้?', 'When was a friend the reason you didn\'t give up?'],
  ['อะไรที่เราสองคนเห็นตรงกันเสมอ?', 'What do we always agree on?'],
  ['อยากให้คนอื่นมองมิตรภาพของเราว่าเป็นแบบไหน?', 'How would you like others to see our friendship?'],
  ['มีสัญญาอะไรที่อยากให้เราสัญญากันในฐานะเพื่อน?', 'What promise would you like us to make as friends?'],
  ['เคยคิดถึงเพื่อนคนนี้ในช่วงไหนที่ไม่คาดคิดบ้าง?', 'When have you thought of this friend at an unexpected moment?'],
  ['การเป็นเพื่อนกันทำให้เรามีความกล้าทางความคิดเรื่องไหนมากขึ้น?', 'In what way has our friendship made you bolder in your thinking?'],
  ['ช่วงไหนที่เพื่อนคนนี้ทำให้เราหัวเราะทั้งที่กำลังร้องไห้?', 'When did this friend make you laugh while you were crying?'],
  ['อะไรคือคุณค่าที่เราสองคนยึดถือเหมือนกัน?', 'What values do we share?'],
  ['มีงานอดิเรกไหนที่อยากชวนเพื่อนมาทำด้วยกันเป็นประจำ?', 'Is there a hobby you\'d like to do regularly with this friend?'],
  ['ถ้าได้ขอบคุณเพื่อนคนนี้ต่อหน้าคนอื่น จะขอบคุณเรื่องอะไร?', 'If you thanked this friend in front of others, what would you thank them for?'],
  ['เพื่อนคนนี้เข้ามาในชีวิตในช่วงเวลาที่เหมาะเจาะยังไง?', 'How did this friend come into your life at just the right time?'],
  ['ตอนนี้เราต้องการกำลังใจเรื่องอะไรมากที่สุด?', 'What do you need encouragement with most right now?'],
]

export const deep = [
  ['มีความฝันอะไรที่ยังไม่เคยเล่าให้ใครฟัง?', 'Is there a dream you\'ve never told anyone?'],
  ['อะไรคือสิ่งที่กลัวที่สุดในตอนนี้?', 'What are you most afraid of right now?'],
  ['อะไรคือสิ่งที่อยากให้เพื่อนรู้เกี่ยวกับตัวเราจริง ๆ?', 'What do you really want your friend to know about you?'],
  ['ช่วงเวลายากลำบากที่ผ่านมาได้เพราะมิตรภาพนี้คืออะไร?', 'What hard time did you get through because of this friendship?'],
  ['มีความเชื่อหรือความคิดไหนที่เปลี่ยนไปในช่วงหลัง?', 'Which of your beliefs or ideas has changed recently?'],
  ['เรื่องไหนที่อยากขอโทษเพื่อนแต่ยังไม่มีโอกาส?', 'Is there something you want to apologize to your friend for but haven\'t had the chance?'],
  ['มีความกลัวข้อไหนที่อยากก้าวข้ามให้ได้ในปีนี้?', 'Which fear do you want to overcome this year?'],
  ['ความหมายของ "เพื่อนแท้" สำหรับเราคืออะไร?', 'What does "a true friend" mean to you?'],
  ['เรื่องอะไรที่คิดว่าคนอื่นเข้าใจเราผิดมาตลอด?', 'What do you think people have always misunderstood about you?'],
  ['อะไรที่อยากทำเพื่อคนอื่นแต่ยังไม่ได้ลงมือ?', 'What would you like to do for others but haven\'t started yet?'],
  ['เคยรู้สึกโดดเดี่ยวแม้อยู่ท่ามกลางเพื่อนไหม?', 'Have you ever felt lonely even surrounded by friends?'],
  ['อะไรที่ทำให้ยากจะขอความช่วยเหลือจากเพื่อน?', 'What makes it hard for you to ask a friend for help?'],
  ['มีด้านไหนของตัวเองที่ยังไม่เคยให้เพื่อนเห็น?', 'Is there a side of yourself you\'ve never shown your friends?'],
  ['เวลาเพื่อนห่างไป เรามักจะคิดว่าเป็นความผิดของตัวเองไหม?', 'When a friend drifts away, do you tend to think it\'s your fault?'],
  ['มิตรภาพไหนที่จบลงแล้วยังค้างคาใจ?', 'Is there a friendship that ended and still weighs on you?'],
  ['อะไรที่ทำให้กลัวว่าจะถูกทิ้งไว้ข้างหลัง?', 'What makes you afraid of being left behind?'],
  ['เคยอิจฉาเพื่อนไหม และรับมือกับความรู้สึกนั้นยังไง?', 'Have you ever envied a friend, and how did you handle it?'],
  ['ความคาดหวังจากสังคมเรื่องไหนที่กดดันเรามากที่สุดตอนนี้?', 'Which social expectation puts the most pressure on you right now?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเป็นคนตลกหรือร่าเริงตลอดเวลา?', 'What makes you feel you always have to be the funny or cheerful one?'],
  ['มีบาดแผลในวัยเด็กที่ส่งผลกับการเป็นเพื่อนของเราไหม?', 'Is there a childhood wound that affects how you are as a friend?'],
  ['เวลาเพื่อนประสบความสำเร็จ มีความรู้สึกอื่นปนนอกจากดีใจไหม?', 'When a friend succeeds, do you ever feel anything besides happiness?'],
  ['อะไรคือความลับที่หนักที่สุดที่เคยเก็บไว้คนเดียว?', 'What is the heaviest secret you\'ve ever kept to yourself?'],
  ['ช่วงไหนที่รู้สึกว่าไม่มีใครเข้าใจเราเลย?', 'When did you feel no one understood you at all?'],
  ['การถูกตัดสินจากเพื่อนทำให้เรารู้สึกยังไง?', 'How does being judged by friends make you feel?'],
  ['มีขอบเขตไหนที่อยากให้เพื่อนเคารพมากขึ้น?', 'Which boundary would you like your friends to respect more?'],
  ['อะไรที่ทำให้เราต้องสวมหน้ากากต่อหน้าคนอื่น?', 'What makes you put on a mask in front of others?'],
  ['ความล้มเหลวครั้งไหนที่ยังรู้สึกอายอยู่?', 'Which failure do you still feel embarrassed about?'],
  ['เวลารู้สึกแย่ เรามักจะหายไปหรือเข้าหาเพื่อน?', 'When you feel low, do you disappear or reach out to friends?'],
  ['อะไรคือสิ่งที่ยังไม่กล้ายอมรับกับตัวเอง?', 'What have you not yet dared to admit to yourself?'],
  ['มีคำพูดไหนจากใครที่ยังทำร้ายใจเราอยู่?', 'Is there something someone said that still hurts you?'],
  ['เรามักจะให้มากกว่ารับในมิตรภาพไหม และรู้สึกยังไงกับมัน?', 'Do you tend to give more than you receive in friendships, and how do you feel about that?'],
  ['ถ้าไม่ต้องกลัวคำตัดสินของใคร อยากใช้ชีวิตแบบไหน?', 'If you didn\'t fear anyone\'s judgment, how would you live?'],
  ['อะไรที่ทำให้รู้สึกว่าไม่เก่งพอเมื่อเทียบกับคนอื่น?', 'What makes you feel not good enough compared to others?'],
  ['การเปรียบเทียบตัวเองกับเพื่อนในโซเชียลส่งผลกับเรายังไง?', 'How does comparing yourself to friends on social media affect you?'],
  ['มีช่วงไหนที่อยากหายไปจากทุกคน และตอนนั้นเกิดอะไรขึ้น?', 'Was there a time you wanted to disappear from everyone, and what was going on?'],
  ['อะไรที่ทำให้กลับมาเชื่อใจเพื่อนอีกครั้งหลังจากผิดหวัง?', 'What helps you trust a friend again after being let down?'],
  ['ความเหงาแบบไหนที่เพื่อนช่วยเติมได้ และแบบไหนที่เติมไม่ได้?', 'What kind of loneliness can friends ease, and what kind can\'t they?'],
  ['มีเรื่องไหนที่เราพูดว่า "ไม่เป็นไร" แต่จริง ๆ แล้วเป็น?', 'What do you say "it\'s fine" about when it really isn\'t?'],
  ['ความกดดันจากครอบครัวเรื่องไหนที่อยากให้เพื่อนเข้าใจ?', 'Which family pressure would you like your friend to understand?'],
  ['อะไรคือความผิดพลาดที่ทำให้เราเติบโตมากที่สุด?', 'Which mistake helped you grow the most?'],
  ['เคยรู้สึกว่าต้องเลือกระหว่างเพื่อนกับความฝันไหม?', 'Have you ever felt you had to choose between friends and your dreams?'],
  ['เราเรียนรู้การเป็นเพื่อนมาจากใคร?', 'Who taught you how to be a friend?'],
  ['มีรูปแบบซ้ำ ๆ ที่เห็นในมิตรภาพของเราไหม?', 'Do you notice any repeating patterns in your friendships?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเข้มแข็งให้คนอื่นเห็น?', 'What makes you feel you have to look strong for others?'],
  ['ช่วงไหนที่เรารู้สึกหลงทางในชีวิตมากที่สุด?', 'When have you felt most lost in life?'],
  ['ถ้าเพื่อนอ่านใจเราได้หนึ่งวัน กลัวเขาจะเห็นอะไร?', 'If your friend could read your mind for a day, what would you fear they\'d see?'],
  ['อะไรคือสิ่งที่ยังให้อภัยตัวเองไม่ได้?', 'What have you not been able to forgive yourself for?'],
  ['เวลาโกรธ จริง ๆ แล้วข้างใต้ความโกรธนั้นคือความรู้สึกอะไร?', 'When you\'re angry, what feeling is usually underneath it?'],
  ['มีความต้องการไหนที่รู้สึกผิดที่จะขอจากเพื่อน?', 'Is there a need you feel guilty asking a friend for?'],
  ['อะไรที่ทำให้กลัวการเปลี่ยนแปลงในชีวิต?', 'What makes you afraid of change in life?'],
  ['ถ้าบอกความกลัวหนึ่งอย่างที่ไม่เคยบอกใคร จะเป็นเรื่องอะไร?', 'If you shared one fear you\'ve never told anyone, what would it be?'],
  ['รู้สึกยังไงกับตัวเองในวันที่ไม่มีใครเห็น?', 'How do you feel about yourself on days no one sees you?'],
  ['ความสำเร็จสำหรับเราหมายถึงอะไรจริง ๆ ไม่ใช่ที่คนอื่นบอก?', 'What does success truly mean to you, not what others say?'],
  ['มีความเชื่อเกี่ยวกับตัวเองแบบไหนที่อยากเลิกเชื่อ?', 'Which belief about yourself would you like to stop believing?'],
  ['อะไรที่ทำให้รู้สึกว่ามีคุณค่าในฐานะคนหนึ่งคน?', 'What makes you feel worthy as a person?'],
  ['มีช่วงไหนที่รู้สึกว่าเพื่อนไม่อยู่ตอนที่ต้องการ?', 'Was there a time a friend wasn\'t there when you needed them?'],
  ['อยากให้เพื่อนรู้อะไรเกี่ยวกับวันที่เราเงียบหายไป?', 'What do you want your friends to know about the times you go quiet?'],
  ['อะไรที่ทำให้กลัวการพูดความรู้สึกจริงกับเพื่อน?', 'What makes you afraid to share your real feelings with friends?'],
  ['มีความโกรธเก่า ๆ ต่อใครที่ยังไม่ได้ปล่อยวาง?', 'Is there old anger toward someone you haven\'t let go of?'],
  ['ช่วงไหนที่เรารู้สึกว่าตัวเองไม่มีค่าที่สุด และอะไรช่วยให้ผ่านมาได้?', 'When did you feel least worthy, and what helped you through?'],
  ['ความเป็นตัวเองกับการเป็นที่ยอมรับ อะไรสำคัญกว่าสำหรับเรา?', 'Which matters more to you: being yourself or being accepted?'],
  ['อะไรคือความเสียใจที่ใหญ่ที่สุดในชีวิตตอนนี้?', 'What is the biggest regret in your life so far?'],
  ['มีความสัมพันธ์ไหนที่สอนให้เรารู้จักขอบเขตของตัวเอง?', 'Which relationship taught you your own boundaries?'],
  ['เวลาไหนที่รู้สึกว่าต้องพิสูจน์ตัวเองกับเพื่อน?', 'When do you feel you have to prove yourself to your friends?'],
  ['อะไรที่ทำให้ยอมรับคำชมได้ยาก?', 'What makes it hard for you to accept compliments?'],
  ['มีความทรงจำวัยเด็กไหนที่อยากให้เพื่อนรู้เพื่อเข้าใจเรามากขึ้น?', 'Which childhood memory would help your friend understand you better?'],
  ['เราหนีความรู้สึกด้วยการทำอะไรบ้าง?', 'What do you do to escape your feelings?'],
  ['อะไรที่ทำให้รู้สึกว่าไม่ได้เป็นส่วนหนึ่งของกลุ่ม?', 'What makes you feel you don\'t belong in a group?'],
  ['ถ้าต้องเลือกระหว่างความจริงที่เจ็บกับคำโกหกที่สบายใจจากเพื่อน จะเลือกอะไร?', 'Would you rather hear a painful truth or a comforting lie from a friend?'],
  ['ความกลัวการถูกปฏิเสธส่งผลต่อมิตรภาพของเรายังไง?', 'How does fear of rejection affect your friendships?'],
  ['มีเรื่องไหนที่เรายังเสียใจว่าไม่ได้ทำให้เพื่อน?', 'Is there something you regret not doing for a friend?'],
  ['อะไรที่ทำให้รู้สึกหมดไฟ และเพื่อนช่วยได้ยังไง?', 'What burns you out, and how can friends help?'],
  ['เวลาทำผิดกับเพื่อน ยากที่สุดตรงไหนในการขอโทษ?', 'When you wrong a friend, what\'s the hardest part of apologizing?'],
  ['ความคาดหวังที่มีต่อตัวเองสูงเกินไปในเรื่องไหน?', 'Where are your expectations of yourself too high?'],
  ['มีส่วนไหนของตัวเองที่กำลังพยายามรักอยู่?', 'Which part of yourself are you learning to love?'],
  ['ช่วงไหนที่รู้สึกว่าโตเร็วเกินไป?', 'When did you feel you had to grow up too fast?'],
  ['อะไรที่ทำให้ไม่กล้าเริ่มต้นสิ่งใหม่?', 'What stops you from starting something new?'],
  ['มิตรภาพที่ดีต่อใจกับมิตรภาพที่เป็นพิษ ต่างกันยังไงในความคิดของเรา?', 'In your view, what\'s the difference between a nourishing friendship and a toxic one?'],
  ['เคยรู้สึกว่าต้องเปลี่ยนตัวเองเพื่อให้เข้ากับเพื่อนไหม?', 'Have you ever felt you had to change yourself to fit in with friends?'],
  ['อะไรคือสิ่งที่อยากได้ยินจากเพื่อนมากที่สุดในวันที่แย่?', 'What do you most want to hear from a friend on a bad day?'],
  ['มีการตัดสินใจครั้งไหนที่ยังสงสัยว่าทำถูกไหม?', 'Is there a decision you still wonder whether you got right?'],
  ['อะไรที่ทำให้รู้สึกว่าชีวิตไม่ยุติธรรม?', 'What makes you feel life is unfair?'],
  ['เวลาไหนที่รู้สึกภูมิใจในตัวเองโดยไม่ต้องมีใครชม?', 'When have you felt proud of yourself without anyone\'s praise?'],
  ['ความกังวลเรื่องอนาคตข้อไหนที่วนอยู่ในหัวบ่อยที่สุด?', 'Which worry about the future loops in your mind most often?'],
  ['มีคนที่อยากขอบคุณแต่ไม่มีโอกาสแล้วไหม?', 'Is there someone you wish you could thank but no longer can?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องทำให้ทุกคนพอใจ?', 'What makes you feel you have to please everyone?'],
  ['ถ้าเลือกได้ อยากเยียวยาความรู้สึกไหนในตัวเองก่อน?', 'If you could heal one feeling in yourself first, which would it be?'],
  ['เราเป็นคนที่รู้ตัวว่าต้องการอะไร หรือยังค้นหาอยู่?', 'Do you know what you want, or are you still searching?'],
  ['มีช่วงไหนที่เพื่อนเห็นศักยภาพในตัวเราก่อนเราเห็นเอง?', 'When did a friend see your potential before you did?'],
  ['ความสัมพันธ์กับตัวเองตอนนี้เป็นยังไง?', 'How is your relationship with yourself right now?'],
  ['อะไรที่ทำให้อยากถอยออกจากมิตรภาพที่ใกล้ชิดเกินไป?', 'What makes you want to pull back when a friendship gets very close?'],
  ['มีความลับไหนที่เก็บไว้เพราะกลัวเพื่อนจะมองเราต่างไป?', 'Is there a secret you keep because you fear friends would see you differently?'],
  ['การให้อภัยคนที่ไม่เคยขอโทษ เป็นไปได้ไหมสำหรับเรา?', 'Is it possible for you to forgive someone who never apologized?'],
  ['อะไรคือสิ่งที่เรียนรู้จากการสูญเสียใครบางคน?', 'What have you learned from losing someone?'],
  ['ช่วงไหนที่เราเป็นเพื่อนที่ไม่ดีนัก และเรียนรู้อะไรจากมัน?', 'When were you not a great friend, and what did you learn from it?'],
  ['อะไรที่ทำให้รู้สึกว่าเสียงของเราไม่สำคัญ?', 'What makes you feel your voice doesn\'t matter?'],
  ['ความฝันที่ถูกคนอื่นบอกว่าเป็นไปไม่ได้ ยังอยู่ในใจไหม?', 'Is a dream others called impossible still in your heart?'],
  ['มีด้านมืดเล็ก ๆ ของตัวเองที่ยอมรับได้แล้วไหม?', 'Is there a small dark side of yourself you\'ve come to accept?'],
  ['อะไรที่ทำให้เราไว้ใจคนได้ยาก?', 'What makes it hard for you to trust people?'],
  ['เวลารู้สึกถูกทิ้ง เรามักตอบสนองยังไง?', 'How do you usually react when you feel abandoned?'],
  ['การอยู่คนเดียวกับการเหงา ต่างกันยังไงสำหรับเรา?', 'For you, what\'s the difference between being alone and being lonely?'],
  ['มีความเชื่อที่ได้รับมาจากครอบครัวแล้วกำลังตั้งคำถามอยู่ไหม?', 'Is there a belief from your family you\'re now questioning?'],
  ['อะไรคือความกลัวที่ซ่อนอยู่หลังความมั่นใจของเรา?', 'What fear hides behind your confidence?'],
  ['ช่วงไหนที่ต้องเลือกตัวเองก่อนคนอื่น และรู้สึกยังไง?', 'When did you have to choose yourself over others, and how did it feel?'],
  ['อยากให้เพื่อนเข้าหาเรายังไงตอนที่เรากำลังมีปัญหาแต่ไม่พูด?', 'How would you like a friend to approach you when you\'re struggling but not saying so?'],
  ['มีคำถามไหนเกี่ยวกับชีวิตที่ยังหาคำตอบไม่ได้?', 'Is there a question about life you still can\'t answer?'],
  ['อะไรที่ทำให้รู้สึกว่าตัวเองเป็นภาระ?', 'What makes you feel like a burden?'],
  ['ความสัมพันธ์ไหนในชีวิตที่สอนเรื่องการปล่อยวาง?', 'Which relationship taught you about letting go?'],
  ['ช่วงไหนที่รู้สึกว่าเรากำลังใช้ชีวิตตามที่คนอื่นต้องการ?', 'When have you felt you were living the life others wanted for you?'],
  ['อะไรที่อยากให้ตัวเองในวัยเด็กรู้?', 'What would you want your younger self to know?'],
  ['ความเปราะบางที่สุดของเราคืออะไร?', 'What is your most vulnerable side?'],
  ['มีความรู้สึกไหนที่ไม่รู้จะเล่าให้ใครฟังดี?', 'Is there a feeling you don\'t know who to talk to about?'],
  ['อะไรที่ทำให้รู้สึกปลอดภัยพอจะเป็นตัวเองต่อหน้าเพื่อน?', 'What makes you feel safe enough to be yourself around friends?'],
  ['เคยรู้สึกว่าเพื่อนไม่ได้ฟังจริง ๆ ตอนไหน และตอนนั้นต้องการอะไร?', 'When did you feel a friend wasn\'t really listening, and what did you need?'],
  ['ความคิดแบบไหนที่มักทำร้ายตัวเองตอนกลางคืน?', 'What kind of thoughts tend to hurt you at night?'],
  ['ช่วงไหนที่ความเชื่อมั่นในตัวเองหายไป และมันกลับมาได้ยังไง?', 'When did your self-confidence disappear, and how did it come back?'],
  ['อะไรที่ทำให้กลัวว่าจะทำให้คนอื่นผิดหวัง?', 'What makes you afraid of disappointing others?'],
  ['มีความต้องการไหนที่เพิ่งรู้ตัวว่ามีเมื่อโตขึ้น?', 'Which need did you only discover as you grew older?'],
  ['การได้รับความช่วยเหลือทำให้รู้สึกอบอุ่นหรืออึดอัด?', 'Does receiving help make you feel warm or uncomfortable?'],
  ['อะไรคือสิ่งที่ทำไปเพื่อให้ได้รับการยอมรับ แต่จริง ๆ ไม่ได้อยากทำ?', 'What do you do to be accepted that you don\'t really want to do?'],
  ['มีความทรงจำที่เจ็บแต่ทำให้มิตรภาพแน่นขึ้นไหม?', 'Is there a painful memory that made a friendship stronger?'],
  ['ความกลัวที่จะเติบโตแยกทางกับเพื่อนมีอยู่ไหม?', 'Are you afraid of growing apart from your friends?'],
  ['อะไรคือความสุขที่กลัวจะเสียไปที่สุด?', 'What happiness are you most afraid of losing?'],
  ['เวลารู้สึกล้มเหลว เราพูดกับตัวเองว่าอะไร?', 'What do you tell yourself when you feel like a failure?'],
  ['มีความเชื่อเรื่องตัวเองแบบไหนที่เพื่อนช่วยเปลี่ยน?', 'Which belief about yourself has a friend helped change?'],
  ['อะไรที่ทำให้อยากเป็นคนที่ดีขึ้น?', 'What makes you want to be a better person?'],
  ['ช่วงไหนที่เราต้องเป็นผู้ใหญ่ให้เพื่อนทั้งที่ข้างในยังเปราะบาง?', 'When did you have to be the grown-up for a friend while feeling fragile inside?'],
  ['มีความกลัวเรื่องความตายหรือการสูญเสียที่อยากคุยไหม?', 'Is there a fear about death or loss you\'d like to talk about?'],
  ['อะไรที่ทำให้รู้สึกว่าชีวิตมีความหมาย?', 'What makes your life feel meaningful?'],
  ['การให้อภัยตัวเองยากกว่าการให้อภัยคนอื่นไหม?', 'Is forgiving yourself harder than forgiving others?'],
  ['มีคำวิจารณ์ไหนที่ยังวนอยู่ในหัวแม้ผ่านมานาน?', 'Is there a criticism that still echoes in your head after all this time?'],
  ['อะไรที่ทำให้รู้สึกว่าเราไม่ได้เป็นตัวเองมาสักพักแล้ว?', 'What makes you feel you haven\'t been yourself for a while?'],
  ['ความสัมพันธ์กับเงินหรือความสำเร็จส่งผลกับคุณค่าในตัวเรายังไง?', 'How does your relationship with money or success affect your self-worth?'],
  ['ถ้าได้คุยกับตัวเองในอีก 10 ปี อยากถามอะไร?', 'If you could talk to yourself ten years from now, what would you ask?'],
  ['มีเรื่องที่ยังไม่พร้อมจะพูด แต่อยากให้เพื่อนรู้ว่ามีอยู่ไหม?', 'Is there something you\'re not ready to talk about but want your friend to know exists?'],
  ['อะไรคือรูปแบบความคิดที่อยากเปลี่ยนในตัวเอง?', 'Which thought pattern would you like to change in yourself?'],
  ['เวลาไหนที่เรารู้สึกขอบคุณชีวิตมากที่สุด?', 'When do you feel most grateful for life?'],
  ['มีความโกรธต่อตัวเองที่ส่งผลกับวิธีที่เราปฏิบัติต่อเพื่อนไหม?', 'Does anger at yourself ever affect how you treat friends?'],
  ['การยอมรับว่าตัวเองไม่ไหว ยากแค่ไหนสำหรับเรา?', 'How hard is it for you to admit you\'re not okay?'],
  ['อะไรที่อยากให้เพื่อนคนนี้จำเกี่ยวกับเราเสมอ?', 'What do you want this friend to always remember about you?'],
  ['มีบทเรียนชีวิตที่ได้มาแบบเจ็บปวดที่สุดคืออะไร?', 'What life lesson did you learn the hardest way?'],
  ['อะไรทำให้รู้สึกว่าเรากำลังเติบโตแม้จะช้า?', 'What makes you feel you\'re growing, even if slowly?'],
  ['มีความรู้สึกที่ไม่มีคำเรียกแต่รู้สึกบ่อย ๆ ไหม?', 'Is there a feeling you often have but have no word for?'],
  ['ความฝันไหนที่ยอมแพ้ไปแล้ว และรู้สึกยังไงกับมันตอนนี้?', 'Which dream did you give up on, and how do you feel about it now?'],
  ['อะไรที่ทำให้เราอยากซ่อนความสำเร็จของตัวเอง?', 'What makes you want to hide your own success?'],
  ['ช่วงไหนที่รู้สึกว่าโลกทั้งใบต่อต้านเรา และใครอยู่ข้างเรา?', 'When did it feel like the whole world was against you, and who stood by you?'],
  ['มีความสัมพันธ์ที่อยากซ่อมแซมแต่ไม่รู้จะเริ่มยังไงไหม?', 'Is there a relationship you\'d like to repair but don\'t know how to start?'],
  ['อะไรที่ทำให้กลัวการถูกมองว่าอ่อนแอ?', 'What makes you afraid of being seen as weak?'],
  ['ความคาดหวังของเราที่มีต่อเพื่อนสูงเกินไปในเรื่องไหน?', 'Where are your expectations of your friends too high?'],
  ['เวลาเห็นเพื่อนเจ็บปวด รู้สึกยังไงข้างใน?', 'How do you feel inside when you see a friend in pain?'],
  ['อะไรคือสิ่งที่ยังไม่เข้าใจในตัวเองเลย?', 'What about yourself do you still not understand?'],
  ['มีช่วงเวลาที่รู้สึกว่าทุกอย่างลงตัวในชีวิตไหม และตอนนั้นเป็นยังไง?', 'Has there been a time everything in life felt in place, and what was it like?'],
  ['อะไรที่ทำให้รู้สึกว่าเราต้องรับผิดชอบความสุขของคนอื่น?', 'What makes you feel responsible for other people\'s happiness?'],
  ['ความสำเร็จของคนอื่นทำให้เรามองตัวเองยังไง?', 'How do other people\'s successes make you see yourself?'],
  ['มีความกลัวในวัยเด็กที่ยังติดตัวมาจนโตไหม?', 'Is there a childhood fear you still carry?'],
  ['อะไรคือสิ่งที่อยากได้รับการยอมรับจากเพื่อนมากที่สุด?', 'What do you most want your friends to acknowledge about you?'],
  ['ช่วงไหนที่เราใจร้ายกับตัวเองมากที่สุด?', 'When have you been hardest on yourself?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องรีบประสบความสำเร็จ?', 'What makes you feel you have to succeed quickly?'],
  ['มิตรภาพนี้ช่วยเยียวยาแผลใจเก่าของเราได้บ้างไหม?', 'Has this friendship helped heal an old wound of yours?'],
  ['มีความต้องการไหนที่มักลดความสำคัญของมันเอง?', 'Which of your needs do you tend to downplay?'],
  ['ถ้าพูดความจริงกับเพื่อนได้หนึ่งเรื่องโดยไม่มีผลกระทบ จะพูดเรื่องอะไร?', 'If you could tell your friend one truth with no consequences, what would it be?'],
  ['อะไรที่ทำให้รู้สึกว่าเราไม่ได้รับการมองเห็น?', 'What makes you feel unseen?'],
  ['ความหวังที่ยังเก็บไว้แม้ชีวิตจะยากคืออะไร?', 'What hope do you hold onto even when life is hard?'],
  ['การเปลี่ยนแปลงในตัวเราที่เพื่อนอาจยังไม่เห็นคืออะไร?', 'What change in you might your friends not have noticed yet?'],
  ['อะไรที่ทำให้อยากเก็บความรู้สึกไว้คนเดียว?', 'What makes you want to keep your feelings to yourself?'],
  ['มีความเชื่อเรื่องความรักหรือมิตรภาพที่แตกสลายไปแล้วไหม?', 'Is there a belief about love or friendship that has shattered for you?'],
  ['อะไรคือความกล้าที่อยากมีมากขึ้น?', 'What kind of courage would you like to have more of?'],
  ['ช่วงไหนที่ได้เรียนรู้ว่าตัวเองแข็งแกร่งกว่าที่คิด?', 'When did you learn you were stronger than you thought?'],
  ['อะไรที่ทำให้รู้สึกว่าเรากำลังวิ่งหนีอะไรบางอย่าง?', 'What makes you feel you\'re running from something?'],
  ['มีคำขอโทษที่อยากได้รับจากใครสักคนไหม?', 'Is there an apology you\'re still waiting for from someone?'],
  ['ความสุขแบบเรียบง่ายที่เราเพิ่งเห็นคุณค่าคืออะไร?', 'What simple happiness have you only recently come to value?'],
  ['ถ้ามิตรภาพนี้เป็นครู มันกำลังสอนบทเรียนอะไรเรา?', 'If this friendship were a teacher, what lesson is it teaching you?'],
  ['อะไรที่ทำให้กลัวว่าจะไม่มีใครจำเราได้?', 'What makes you afraid of being forgotten?'],
  ['มีส่วนไหนในชีวิตที่รู้สึกว่ายังไม่ได้เป็นเจ้าของจริง ๆ?', 'Which part of your life do you feel you don\'t truly own yet?'],
  ['เวลาไหนที่เรารู้สึกว่าเป็นตัวเองมากที่สุด?', 'When do you feel most like yourself?'],
  ['อะไรคือความเจ็บปวดที่ไม่ค่อยมีใครรู้ว่าเรามี?', 'What pain do you carry that few people know about?'],
  ['มีความเชื่อใจที่เคยพังแล้วสร้างใหม่ได้ไหม?', 'Have you ever rebuilt trust after it was broken?'],
  ['อะไรที่ทำให้อยากหยุดพักจากผู้คน?', 'What makes you want a break from people?'],
  ['ความสัมพันธ์กับร่างกายตัวเองเป็นยังไงในช่วงนี้?', 'How is your relationship with your body lately?'],
  ['มีบทสนทนาไหนที่ยังค้างคาและอยากกลับไปคุยให้จบ?', 'Is there an unfinished conversation you\'d like to return to?'],
  ['อะไรที่ทำให้รู้สึกว่าต้องเป็นคนที่สมบูรณ์แบบ?', 'What makes you feel you have to be perfect?'],
  ['ช่วงไหนที่เพื่อนเป็นคนเดียวที่เรากล้าเปิดใจด้วย?', 'When was a friend the only person you dared to open up to?'],
  ['อะไรคือสิ่งที่หวังว่าคนอื่นจะถามเรามากกว่านี้?', 'What do you wish people asked you about more?'],
  ['มีความรู้สึกผิดที่แบกไว้นานเกินไปไหม?', 'Is there guilt you\'ve carried for too long?'],
  ['อะไรที่ทำให้ใจเราอ่อนลงแม้กำลังโกรธอยู่?', 'What softens your heart even when you\'re angry?'],
  ['ชีวิตแบบไหนที่จะทำให้รู้สึกว่า "คุ้มแล้ว" ตอนแก่?', 'What kind of life would make you feel "it was worth it" when you\'re old?'],
  ['มีความกลัวว่าจะกลายเป็นคนแบบไหน?', 'What kind of person are you afraid of becoming?'],
  ['อะไรที่ทำให้รู้สึกว่าเพื่อนคนนี้ปลอดภัยพอจะรู้เรื่องทั้งหมดของเรา?', 'What makes this friend safe enough to know everything about you?'],
  ['เคยรู้สึกว่าต้องแข่งกับเพื่อนสนิทโดยไม่ได้ตั้งใจไหม?', 'Have you ever felt yourself competing with a close friend without meaning to?'],
  ['อะไรที่ทำให้รู้สึกว่ามิตรภาพนี้ไม่เท่ากัน และอยากให้เป็นยังไง?', 'What makes a friendship feel uneven to you, and how would you like it to be?'],
  ['ความเงียบระหว่างเพื่อนทำให้เรารู้สึกสบายหรือกังวล?', 'Does silence between friends feel comfortable or worrying to you?'],
  ['มีคนที่เราเลิกคบไปแล้วแต่ยังคิดถึงไหม?', 'Is there someone you stopped being friends with but still miss?'],
  ['อะไรคือสิ่งที่อยากให้เพื่อนรู้เกี่ยวกับสุขภาพใจของเราตอนนี้?', 'What would you like your friend to know about your mental health right now?'],
  ['เวลาไหนที่เราเห็นตัวเองในเพื่อนคนนี้ชัดที่สุด?', 'When do you see yourself most clearly in this friend?'],
  ['เราแสดงความรักกับเพื่อนแบบไหน และอยากได้รับแบบไหน?', 'How do you show love to friends, and how do you like to receive it?'],
  ['มีความคาดหวังที่ไม่เคยพูดออกมาแต่หวังว่าเพื่อนจะเข้าใจไหม?', 'Is there an unspoken expectation you hope your friend will understand?'],
  ['ถ้ามิตรภาพนี้จบลงพรุ่งนี้ อะไรคือสิ่งที่ยังไม่ได้บอก?', 'If this friendship ended tomorrow, what would you still not have said?'],
  ['อะไรคือสิ่งที่ยังต้องเรียนรู้ในการเป็นเพื่อนที่ดีขึ้น?', 'What do you still need to learn to be a better friend?'],
  ['ถ้าคืนนี้พูดความจริงได้ทุกเรื่องโดยไม่มีใครเจ็บ อยากพูดเรื่องอะไรก่อน?', 'If we could speak every truth tonight without anyone getting hurt, what would you say first?'],
  ['มิตรภาพนี้ทำให้เราเชื่อในอะไรมากขึ้น?', 'What has this friendship made you believe in more?'],
]
